// Content data: full official HSK1 (150) + HSK2 (149 unique cards) vocabulary,
// 24 core HSK1-2 grammar points, and a bank of longer/advanced sentences for
// the Listen and Speak "Sentences" mode. Traditional characters (Taiwan usage)
// + Hanyu Pinyin. Feel free to extend any of these arrays.

const VOCAB = [
  { id: "v1", hanzi: "愛", pinyin: "ài", en: "to love", level: "HSK1", ex: { hanzi: "我愛我的家人。", pinyin: "Wǒ ài wǒ de jiā rén.", en: "I love my family." } },
  { id: "v2", hanzi: "八", pinyin: "bā", en: "eight", level: "HSK1", ex: { hanzi: "我有八本書。", pinyin: "Wǒ yǒu bā běn shū.", en: "I have eight books." } },
  { id: "v3", hanzi: "爸爸", pinyin: "bàba", en: "dad", level: "HSK1", ex: { hanzi: "爸爸在工作。", pinyin: "Bàba zài gōng zuò.", en: "Dad is working." } },
  { id: "v4", hanzi: "杯子", pinyin: "bēizi", en: "cup", level: "HSK1", ex: { hanzi: "這個杯子是我的。", pinyin: "Zhè gè bēi zi shì wǒ de.", en: "This cup is mine." } },
  { id: "v5", hanzi: "北京", pinyin: "běijīng", en: "Beijing", level: "HSK1", ex: { hanzi: "我想去北京。", pinyin: "Wǒ xiǎng qù běi jīng.", en: "I want to go to Beijing." } },
  { id: "v6", hanzi: "本", pinyin: "běn", en: "(measure word for books)", level: "HSK1", ex: { hanzi: "我買了三本書。", pinyin: "Wǒ mǎi le sān běn shū.", en: "I bought three books." } },
  { id: "v7", hanzi: "不客氣", pinyin: "búkèqì", en: "you're welcome", level: "HSK1", ex: { hanzi: "不客氣，再見。", pinyin: "Bù kè qì zài jiàn.", en: "You're welcome, goodbye." } },
  { id: "v8", hanzi: "不", pinyin: "bù", en: "not / no", level: "HSK1", ex: { hanzi: "我不是老師。", pinyin: "Wǒ bù shì lǎo shī.", en: "I am not a teacher." } },
  { id: "v9", hanzi: "菜", pinyin: "cài", en: "dish / vegetable", level: "HSK1", ex: { hanzi: "這個菜很好吃。", pinyin: "Zhè gè cài hěn hǎo chī.", en: "This dish is delicious." } },
  { id: "v10", hanzi: "茶", pinyin: "chá", en: "tea", level: "HSK1", ex: { hanzi: "臺灣的茶很有名。", pinyin: "Tái wān de chá hěn yǒu míng.", en: "Taiwan's tea is famous." } },
  { id: "v11", hanzi: "吃", pinyin: "chī", en: "to eat", level: "HSK1", ex: { hanzi: "你吃早飯了嗎？", pinyin: "Nǐ chī zǎo fàn le ma?", en: "Have you eaten breakfast?" } },
  { id: "v12", hanzi: "計程車", pinyin: "chūzūchē", en: "taxi", level: "HSK1", ex: { hanzi: "我們坐計程車去吧。", pinyin: "Wǒ men zuò chū zū chē qù ba.", en: "Let's take a taxi." } },
  { id: "v13", hanzi: "打電話", pinyin: "dǎdiànhuà", en: "to make a phone call", level: "HSK1", ex: { hanzi: "我要給他打電話。", pinyin: "Wǒ yào gěi tā dǎ diàn huà.", en: "I want to call him." } },
  { id: "v14", hanzi: "大", pinyin: "dà", en: "big", level: "HSK1", ex: { hanzi: "這間房子很大。", pinyin: "Zhè jiān fáng zi hěn dà.", en: "This house is big." } },
  { id: "v15", hanzi: "的", pinyin: "de", en: "possessive particle", level: "HSK1", ex: { hanzi: "這是我的書。", pinyin: "Zhè shì wǒ de shū.", en: "This is my book." } },
  { id: "v16", hanzi: "點", pinyin: "diǎn", en: "o'clock / a little", level: "HSK1", ex: { hanzi: "現在幾點？", pinyin: "Xiàn zài jǐ diǎn?", en: "What time is it now?" } },
  { id: "v17", hanzi: "電腦", pinyin: "diànnǎo", en: "computer", level: "HSK1", ex: { hanzi: "我的電腦壞了。", pinyin: "Wǒ de diàn nǎo huài le.", en: "My computer is broken." } },
  { id: "v18", hanzi: "電視", pinyin: "diànshì", en: "television", level: "HSK1", ex: { hanzi: "我在看電視。", pinyin: "Wǒ zài kàn diàn shì.", en: "I'm watching TV." } },
  { id: "v19", hanzi: "電影", pinyin: "diànyǐng", en: "movie", level: "HSK1", ex: { hanzi: "我們去看電影吧。", pinyin: "Wǒ men qù kàn diàn yǐng ba.", en: "Let's go watch a movie." } },
  { id: "v20", hanzi: "東西", pinyin: "dōngxi", en: "thing", level: "HSK1", ex: { hanzi: "這是什麼東西？", pinyin: "Zhè shì shén me dōngxi?", en: "What is this thing?" } },
  { id: "v21", hanzi: "都", pinyin: "dōu", en: "all / both", level: "HSK1", ex: { hanzi: "我們都是學生。", pinyin: "Wǒ men dōu shì xué shēng.", en: "We are all students." } },
  { id: "v22", hanzi: "讀", pinyin: "dú", en: "to read (aloud)", level: "HSK1", ex: { hanzi: "請大聲讀。", pinyin: "Qǐng dà shēng dú.", en: "Please read aloud." } },
  { id: "v23", hanzi: "對不起", pinyin: "duìbùqǐ", en: "sorry", level: "HSK1", ex: { hanzi: "對不起，我遲到了。", pinyin: "Duì bù qǐ wǒ chí dào le.", en: "Sorry, I'm late." } },
  { id: "v24", hanzi: "多", pinyin: "duō", en: "many / much", level: "HSK1", ex: { hanzi: "他有很多朋友。", pinyin: "Tā yǒu hěn duō péng yǒu.", en: "He has many friends." } },
  { id: "v25", hanzi: "多少", pinyin: "duōshǎo", en: "how much / many", level: "HSK1", ex: { hanzi: "這個多少錢？", pinyin: "Zhè gè duō shǎo qián?", en: "How much is this?" } },
  { id: "v26", hanzi: "兒子", pinyin: "érzi", en: "son", level: "HSK1", ex: { hanzi: "我有一個兒子。", pinyin: "Wǒ yǒu yī gè ér zi.", en: "I have a son." } },
  { id: "v27", hanzi: "二", pinyin: "èr", en: "two", level: "HSK1", ex: { hanzi: "二月很冷。", pinyin: "Èr yuè hěn lěng.", en: "February is cold." } },
  { id: "v28", hanzi: "飯店", pinyin: "fàndiàn", en: "restaurant / hotel", level: "HSK1", ex: { hanzi: "我們在飯店吃飯。", pinyin: "Wǒ men zài fàn diàn chī fàn.", en: "We're eating at the restaurant." } },
  { id: "v29", hanzi: "飛機", pinyin: "fēijī", en: "airplane", level: "HSK1", ex: { hanzi: "我坐飛機去臺北。", pinyin: "Wǒ zuò fēi jī qù tái běi.", en: "I'm taking a plane to Taipei." } },
  { id: "v30", hanzi: "分鐘", pinyin: "fēnzhōng", en: "minute", level: "HSK1", ex: { hanzi: "等我五分鐘。", pinyin: "Děng wǒ wǔ fēn zhōng.", en: "Wait for me five minutes." } },
  { id: "v31", hanzi: "高興", pinyin: "gāoxìng", en: "happy", level: "HSK1", ex: { hanzi: "很高興認識你。", pinyin: "Hěn gāo xīng rènshi nǐ.", en: "Nice to meet you." } },
  { id: "v32", hanzi: "個", pinyin: "gè", en: "(general measure word)", level: "HSK1", ex: { hanzi: "我有一個哥哥。", pinyin: "Wǒ yǒu yī gè gēge.", en: "I have one older brother." } },
  { id: "v33", hanzi: "工作", pinyin: "gōngzuò", en: "work / job", level: "HSK1", ex: { hanzi: "他的工作很忙。", pinyin: "Tā de gōng zuò hěn máng.", en: "His job is very busy." } },
  { id: "v34", hanzi: "狗", pinyin: "gǒu", en: "dog", level: "HSK1", ex: { hanzi: "我家有一隻狗。", pinyin: "Wǒ jiā yǒu yī zhǐ gǒu.", en: "My family has a dog." } },
  { id: "v35", hanzi: "漢語", pinyin: "hànyǔ", en: "Chinese language", level: "HSK1", ex: { hanzi: "我在學漢語。", pinyin: "Wǒ zài xué hàn yǔ.", en: "I'm learning Chinese." } },
  { id: "v36", hanzi: "好", pinyin: "hǎo", en: "good", level: "HSK1", ex: { hanzi: "今天天氣很好。", pinyin: "Jīn tiān tiān qì hěn hǎo.", en: "The weather is good today." } },
  { id: "v37", hanzi: "號", pinyin: "hào", en: "number / date", level: "HSK1", ex: { hanzi: "今天幾號？", pinyin: "Jīn tiān jǐ hào?", en: "What's today's date?" } },
  { id: "v38", hanzi: "喝", pinyin: "hē", en: "to drink", level: "HSK1", ex: { hanzi: "我想喝水。", pinyin: "Wǒ xiǎng hē shuǐ.", en: "I want to drink water." } },
  { id: "v39", hanzi: "和", pinyin: "hé", en: "and", level: "HSK1", ex: { hanzi: "我和朋友去看電影。", pinyin: "Wǒ hé péng yǒu qù kàn diàn yǐng.", en: "My friend and I are going to see a movie." } },
  { id: "v40", hanzi: "很", pinyin: "hěn", en: "very", level: "HSK1", ex: { hanzi: "今天很熱。", pinyin: "Jīn tiān hěn rè.", en: "Today is very hot." } },
  { id: "v41", hanzi: "後面", pinyin: "hòumiàn", en: "behind", level: "HSK1", ex: { hanzi: "學校在銀行後面。", pinyin: "Xué xiào zài yín xíng hòu miàn.", en: "The school is behind the bank." } },
  { id: "v42", hanzi: "回", pinyin: "huí", en: "to return", level: "HSK1", ex: { hanzi: "我要回家了。", pinyin: "Wǒ yào huí jiā le.", en: "I'm going home." } },
  { id: "v43", hanzi: "會", pinyin: "huì", en: "can (learned skill)", level: "HSK1", ex: { hanzi: "我會說中文。", pinyin: "Wǒ huì shuō zhōng wén.", en: "I can speak Chinese." } },
  { id: "v44", hanzi: "幾", pinyin: "jǐ", en: "how many (small number)", level: "HSK1", ex: { hanzi: "你家有幾個人？", pinyin: "Nǐ jiā yǒu jǐ gè rén?", en: "How many people are in your family?" } },
  { id: "v45", hanzi: "家", pinyin: "jiā", en: "home / family", level: "HSK1", ex: { hanzi: "我想回家。", pinyin: "Wǒ xiǎng huí jiā.", en: "I want to go home." } },
  { id: "v46", hanzi: "叫", pinyin: "jiào", en: "to be called", level: "HSK1", ex: { hanzi: "你叫什麼名字？", pinyin: "Nǐ jiào shén me míngzi?", en: "What is your name?" } },
  { id: "v47", hanzi: "今天", pinyin: "jīntiān", en: "today", level: "HSK1", ex: { hanzi: "今天天氣很好。", pinyin: "Jīn tiān tiān qì hěn hǎo.", en: "The weather is nice today." } },
  { id: "v48", hanzi: "九", pinyin: "jiǔ", en: "nine", level: "HSK1", ex: { hanzi: "現在九點。", pinyin: "Xiàn zài jiǔ diǎn.", en: "It's nine o'clock now." } },
  { id: "v49", hanzi: "開", pinyin: "kāi", en: "to open / turn on", level: "HSK1", ex: { hanzi: "請開門。", pinyin: "Qǐng kāi mén.", en: "Please open the door." } },
  { id: "v50", hanzi: "看", pinyin: "kàn", en: "to see / watch", level: "HSK1", ex: { hanzi: "我喜歡看電影。", pinyin: "Wǒ xǐ huān kàn diàn yǐng.", en: "I like watching movies." } },
  { id: "v51", hanzi: "看見", pinyin: "kànjiàn", en: "to see / catch sight of", level: "HSK1", ex: { hanzi: "我看見他了。", pinyin: "Wǒ kàn jiàn tā le.", en: "I saw him." } },
  { id: "v52", hanzi: "塊", pinyin: "kuài", en: "(measure word for money) / piece", level: "HSK1", ex: { hanzi: "這個五塊錢。", pinyin: "Zhè gè wǔ kuài qián.", en: "This is five kuai." } },
  { id: "v53", hanzi: "來", pinyin: "lái", en: "to come", level: "HSK1", ex: { hanzi: "你可以來我家。", pinyin: "Nǐ kě yǐ lái wǒ jiā.", en: "You can come to my house." } },
  { id: "v54", hanzi: "老師", pinyin: "lǎoshī", en: "teacher", level: "HSK1", ex: { hanzi: "老師，我有問題。", pinyin: "Lǎo shī wǒ yǒu wèn tí.", en: "Teacher, I have a question." } },
  { id: "v55", hanzi: "了", pinyin: "le", en: "completed-action particle", level: "HSK1", ex: { hanzi: "我吃了。", pinyin: "Wǒ chī le.", en: "I've eaten." } },
  { id: "v56", hanzi: "冷", pinyin: "lěng", en: "cold", level: "HSK1", ex: { hanzi: "今天很冷。", pinyin: "Jīn tiān hěn lěng.", en: "It's cold today." } },
  { id: "v57", hanzi: "裡", pinyin: "lǐ", en: "inside", level: "HSK1", ex: { hanzi: "書在包裡。", pinyin: "Shū zài bāo lǐ.", en: "The book is in the bag." } },
  { id: "v58", hanzi: "六", pinyin: "liù", en: "six", level: "HSK1", ex: { hanzi: "現在六點半。", pinyin: "Xiàn zài liù diǎn bàn.", en: "It's six thirty now." } },
  { id: "v59", hanzi: "嗎", pinyin: "ma", en: "question particle", level: "HSK1", ex: { hanzi: "你是學生嗎？", pinyin: "Nǐ shì xué shēng ma?", en: "Are you a student?" } },
  { id: "v60", hanzi: "媽媽", pinyin: "māma", en: "mom", level: "HSK1", ex: { hanzi: "媽媽在做飯。", pinyin: "Māma zài zuò fàn.", en: "Mom is cooking." } },
  { id: "v61", hanzi: "買", pinyin: "mǎi", en: "to buy", level: "HSK1", ex: { hanzi: "我想買一本書。", pinyin: "Wǒ xiǎng mǎi yī běn shū.", en: "I want to buy a book." } },
  { id: "v62", hanzi: "貓", pinyin: "māo", en: "cat", level: "HSK1", ex: { hanzi: "這隻貓很小。", pinyin: "Zhè zhǐ māo hěn xiǎo.", en: "This cat is small." } },
  { id: "v63", hanzi: "沒關係", pinyin: "méiguānxi", en: "it's okay / no problem", level: "HSK1", ex: { hanzi: "沒關係，不用擔心。", pinyin: "Méiguānxi bù yòng dān xīn.", en: "It's fine, don't worry." } },
  { id: "v64", hanzi: "沒有", pinyin: "méiyǒu", en: "to not have", level: "HSK1", ex: { hanzi: "我沒有錢。", pinyin: "Wǒ méi yǒu qián.", en: "I don't have money." } },
  { id: "v65", hanzi: "米飯", pinyin: "mǐfàn", en: "(cooked) rice", level: "HSK1", ex: { hanzi: "我想吃米飯。", pinyin: "Wǒ xiǎng chī mǐ fàn.", en: "I want to eat rice." } },
  { id: "v66", hanzi: "名字", pinyin: "míngzi", en: "name", level: "HSK1", ex: { hanzi: "你的名字是什麼？", pinyin: "Nǐ de míngzi shì shén me?", en: "What is your name?" } },
  { id: "v67", hanzi: "明天", pinyin: "míngtiān", en: "tomorrow", level: "HSK1", ex: { hanzi: "明天我要工作。", pinyin: "Míng tiān wǒ yào gōng zuò.", en: "I have to work tomorrow." } },
  { id: "v68", hanzi: "哪", pinyin: "nǎ", en: "which", level: "HSK1", ex: { hanzi: "你要哪個？", pinyin: "Nǐ yào nǎ gè?", en: "Which one do you want?" } },
  { id: "v69", hanzi: "哪兒", pinyin: "nǎr", en: "where", level: "HSK1", ex: { hanzi: "你在哪兒？", pinyin: "Nǐ zài nǎr?", en: "Where are you?" } },
  { id: "v70", hanzi: "那", pinyin: "nà", en: "that", level: "HSK1", ex: { hanzi: "那是我的家。", pinyin: "Nà shì wǒ de jiā.", en: "That is my home." } },
  { id: "v71", hanzi: "呢", pinyin: "ne", en: "question particle (topic)", level: "HSK1", ex: { hanzi: "我很好，你呢？", pinyin: "Wǒ hěn hǎo nǐ ne?", en: "I'm good, and you?" } },
  { id: "v72", hanzi: "能", pinyin: "néng", en: "to be able to", level: "HSK1", ex: { hanzi: "我能幫你。", pinyin: "Wǒ néng bāng nǐ.", en: "I can help you." } },
  { id: "v73", hanzi: "你", pinyin: "nǐ", en: "you", level: "HSK1", ex: { hanzi: "你好嗎？", pinyin: "Nǐ hǎo ma?", en: "How are you?" } },
  { id: "v74", hanzi: "年", pinyin: "nián", en: "year", level: "HSK1", ex: { hanzi: "我今年二十歲。", pinyin: "Wǒ jīn nián èr shí suì.", en: "I am twenty years old this year." } },
  { id: "v75", hanzi: "女兒", pinyin: "nǚ'ér", en: "daughter", level: "HSK1", ex: { hanzi: "我有一個女兒。", pinyin: "Wǒ yǒu yī gè nǚ'ér.", en: "I have a daughter." } },
  { id: "v76", hanzi: "朋友", pinyin: "péngyǒu", en: "friend", level: "HSK1", ex: { hanzi: "他是我最好的朋友。", pinyin: "Tā shì wǒ zuì hǎo de péng yǒu.", en: "He's my best friend." } },
  { id: "v77", hanzi: "漂亮", pinyin: "piàoliang", en: "pretty", level: "HSK1", ex: { hanzi: "她很漂亮。", pinyin: "Tā hěn piàoliang.", en: "She is pretty." } },
  { id: "v78", hanzi: "蘋果", pinyin: "píngguǒ", en: "apple", level: "HSK1", ex: { hanzi: "這個蘋果很甜。", pinyin: "Zhè gè píng guǒ hěn tián.", en: "This apple is sweet." } },
  { id: "v79", hanzi: "七", pinyin: "qī", en: "seven", level: "HSK1", ex: { hanzi: "現在七點。", pinyin: "Xiàn zài qī diǎn.", en: "It's seven o'clock." } },
  { id: "v80", hanzi: "前面", pinyin: "qiánmiàn", en: "in front", level: "HSK1", ex: { hanzi: "老師在前面。", pinyin: "Lǎo shī zài qián miàn.", en: "The teacher is at the front." } },
  { id: "v81", hanzi: "錢", pinyin: "qián", en: "money", level: "HSK1", ex: { hanzi: "我沒有錢。", pinyin: "Wǒ méi yǒu qián.", en: "I don't have money." } },
  { id: "v82", hanzi: "請", pinyin: "qǐng", en: "please / to invite", level: "HSK1", ex: { hanzi: "請坐。", pinyin: "Qǐng zuò.", en: "Please sit." } },
  { id: "v83", hanzi: "去", pinyin: "qù", en: "to go", level: "HSK1", ex: { hanzi: "我要去學校。", pinyin: "Wǒ yào qù xué xiào.", en: "I'm going to school." } },
  { id: "v84", hanzi: "熱", pinyin: "rè", en: "hot", level: "HSK1", ex: { hanzi: "夏天很熱。", pinyin: "Xià tiān hěn rè.", en: "Summer is hot." } },
  { id: "v85", hanzi: "人", pinyin: "rén", en: "person", level: "HSK1", ex: { hanzi: "這個人是誰？", pinyin: "Zhè gè rén shì shéi?", en: "Who is this person?" } },
  { id: "v86", hanzi: "認識", pinyin: "rènshi", en: "to know (a person)", level: "HSK1", ex: { hanzi: "很高興認識你。", pinyin: "Hěn gāo xīng rènshi nǐ.", en: "Nice to meet you." } },
  { id: "v87", hanzi: "三", pinyin: "sān", en: "three", level: "HSK1", ex: { hanzi: "他有三本書。", pinyin: "Tā yǒu sān běn shū.", en: "He has three books." } },
  { id: "v88", hanzi: "商店", pinyin: "shāngdiàn", en: "store", level: "HSK1", ex: { hanzi: "我要去商店買東西。", pinyin: "Wǒ yào qù shāng diàn mǎi dōngxi.", en: "I'm going to the store to buy things." } },
  { id: "v89", hanzi: "上", pinyin: "shàng", en: "on / above", level: "HSK1", ex: { hanzi: "書在桌子上。", pinyin: "Shū zài zhuō zi shàng.", en: "The book is on the table." } },
  { id: "v90", hanzi: "上午", pinyin: "shàngwǔ", en: "morning", level: "HSK1", ex: { hanzi: "我上午有課。", pinyin: "Wǒ shàng wǔ yǒu kè.", en: "I have class in the morning." } },
  { id: "v91", hanzi: "少", pinyin: "shǎo", en: "few / little", level: "HSK1", ex: { hanzi: "他的錢很少。", pinyin: "Tā de qián hěn shǎo.", en: "He has very little money." } },
  { id: "v92", hanzi: "誰", pinyin: "shéi", en: "who", level: "HSK1", ex: { hanzi: "他是誰？", pinyin: "Tā shì shéi?", en: "Who is he?" } },
  { id: "v93", hanzi: "什麼", pinyin: "shénme", en: "what", level: "HSK1", ex: { hanzi: "你叫什麼名字？", pinyin: "Nǐ jiào shén me míngzi?", en: "What is your name?" } },
  { id: "v94", hanzi: "十", pinyin: "shí", en: "ten", level: "HSK1", ex: { hanzi: "十分鐘後見。", pinyin: "Shí fēn zhōng hòu jiàn.", en: "See you in ten minutes." } },
  { id: "v95", hanzi: "時候", pinyin: "shíhòu", en: "time / moment", level: "HSK1", ex: { hanzi: "你什麼時候回家？", pinyin: "Nǐ shén me shí hòu huí jiā?", en: "When are you going home?" } },
  { id: "v96", hanzi: "是", pinyin: "shì", en: "to be", level: "HSK1", ex: { hanzi: "我是學生。", pinyin: "Wǒ shì xué shēng.", en: "I am a student." } },
  { id: "v97", hanzi: "書", pinyin: "shū", en: "book", level: "HSK1", ex: { hanzi: "這是我的書。", pinyin: "Zhè shì wǒ de shū.", en: "This is my book." } },
  { id: "v98", hanzi: "水", pinyin: "shuǐ", en: "water", level: "HSK1", ex: { hanzi: "請給我一杯水。", pinyin: "Qǐng gěi wǒ yī bēi shuǐ.", en: "Please give me a glass of water." } },
  { id: "v99", hanzi: "水果", pinyin: "shuǐguǒ", en: "fruit", level: "HSK1", ex: { hanzi: "我喜歡吃水果。", pinyin: "Wǒ xǐ huān chī shuǐ guǒ.", en: "I like eating fruit." } },
  { id: "v100", hanzi: "睡覺", pinyin: "shuìjiào", en: "to sleep", level: "HSK1", ex: { hanzi: "我要去睡覺了。", pinyin: "Wǒ yào qù shuì jué le.", en: "I'm going to sleep." } },
  { id: "v101", hanzi: "說", pinyin: "shuō", en: "to speak", level: "HSK1", ex: { hanzi: "他說中文說得很好。", pinyin: "Tā shuō zhōng wén shuō de hěn hǎo.", en: "He speaks Chinese very well." } },
  { id: "v102", hanzi: "四", pinyin: "sì", en: "four", level: "HSK1", ex: { hanzi: "現在四點。", pinyin: "Xiàn zài sì diǎn.", en: "It's four o'clock." } },
  { id: "v103", hanzi: "歲", pinyin: "suì", en: "years old", level: "HSK1", ex: { hanzi: "我三十歲了。", pinyin: "Wǒ sān shí suì le.", en: "I'm thirty years old." } },
  { id: "v104", hanzi: "他", pinyin: "tā", en: "he", level: "HSK1", ex: { hanzi: "他是我朋友。", pinyin: "Tā shì wǒ péng yǒu.", en: "He is my friend." } },
  { id: "v105", hanzi: "她", pinyin: "tā", en: "she", level: "HSK1", ex: { hanzi: "她是老師。", pinyin: "Tā shì lǎo shī.", en: "She is a teacher." } },
  { id: "v106", hanzi: "太", pinyin: "tài", en: "too (excessively)", level: "HSK1", ex: { hanzi: "這個太貴了。", pinyin: "Zhè gè tài guì le.", en: "This is too expensive." } },
  { id: "v107", hanzi: "天氣", pinyin: "tiānqì", en: "weather", level: "HSK1", ex: { hanzi: "今天天氣很好。", pinyin: "Jīn tiān tiān qì hěn hǎo.", en: "The weather is good today." } },
  { id: "v108", hanzi: "聽", pinyin: "tīng", en: "to listen", level: "HSK1", ex: { hanzi: "我在聽音樂。", pinyin: "Wǒ zài tīng yīn lè.", en: "I'm listening to music." } },
  { id: "v109", hanzi: "同學", pinyin: "tóngxué", en: "classmate", level: "HSK1", ex: { hanzi: "他是我的同學。", pinyin: "Tā shì wǒ de tóng xué.", en: "He is my classmate." } },
  { id: "v110", hanzi: "喂", pinyin: "wèi", en: "hello (on phone)", level: "HSK1", ex: { hanzi: "喂，你好！", pinyin: "Wèi nǐ hǎo!", en: "Hello!" } },
  { id: "v111", hanzi: "我", pinyin: "wǒ", en: "I / me", level: "HSK1", ex: { hanzi: "我是學生。", pinyin: "Wǒ shì xué shēng.", en: "I am a student." } },
  { id: "v112", hanzi: "我們", pinyin: "wǒmen", en: "we / us", level: "HSK1", ex: { hanzi: "我們是朋友。", pinyin: "Wǒ men shì péng yǒu.", en: "We are friends." } },
  { id: "v113", hanzi: "五", pinyin: "wǔ", en: "five", level: "HSK1", ex: { hanzi: "五點下班。", pinyin: "Wǔ diǎn xià bān.", en: "Work ends at five." } },
  { id: "v114", hanzi: "喜歡", pinyin: "xǐhuān", en: "to like", level: "HSK1", ex: { hanzi: "我喜歡喝茶。", pinyin: "Wǒ xǐ huān hē chá.", en: "I like drinking tea." } },
  { id: "v115", hanzi: "下", pinyin: "xià", en: "down / next", level: "HSK1", ex: { hanzi: "下個星期我很忙。", pinyin: "Xià gè xīng qī wǒ hěn máng.", en: "I'm busy next week." } },
  { id: "v116", hanzi: "下午", pinyin: "xiàwǔ", en: "afternoon", level: "HSK1", ex: { hanzi: "下午我要工作。", pinyin: "Xià wǔ wǒ yào gōng zuò.", en: "I have to work in the afternoon." } },
  { id: "v117", hanzi: "下雨", pinyin: "xiàyǔ", en: "to rain", level: "HSK1", ex: { hanzi: "今天下雨。", pinyin: "Jīn tiān xià yǔ.", en: "It's raining today." } },
  { id: "v118", hanzi: "先生", pinyin: "xiānshēng", en: "Mr. / husband", level: "HSK1", ex: { hanzi: "王先生是老師。", pinyin: "Wáng xiān shēng shì lǎo shī.", en: "Mr. Wang is a teacher." } },
  { id: "v119", hanzi: "現在", pinyin: "xiànzài", en: "now", level: "HSK1", ex: { hanzi: "你現在在哪裡？", pinyin: "Nǐ xiàn zài zài nǎ lǐ?", en: "Where are you now?" } },
  { id: "v120", hanzi: "想", pinyin: "xiǎng", en: "to want / think", level: "HSK1", ex: { hanzi: "我想去臺灣。", pinyin: "Wǒ xiǎng qù tái wān.", en: "I'd like to go to Taiwan." } },
  { id: "v121", hanzi: "小", pinyin: "xiǎo", en: "small", level: "HSK1", ex: { hanzi: "這隻貓很小。", pinyin: "Zhè zhǐ māo hěn xiǎo.", en: "This cat is small." } },
  { id: "v122", hanzi: "小姐", pinyin: "xiǎojiě", en: "Miss", level: "HSK1", ex: { hanzi: "王小姐很漂亮。", pinyin: "Wáng xiǎo jiě hěn piàoliang.", en: "Miss Wang is pretty." } },
  { id: "v123", hanzi: "些", pinyin: "xiē", en: "some", level: "HSK1", ex: { hanzi: "我買了一些水果。", pinyin: "Wǒ mǎi le yī xiē shuǐ guǒ.", en: "I bought some fruit." } },
  { id: "v124", hanzi: "寫", pinyin: "xiě", en: "to write", level: "HSK1", ex: { hanzi: "請寫你的名字。", pinyin: "Qǐng xiě nǐ de míngzi.", en: "Please write your name." } },
  { id: "v125", hanzi: "謝謝", pinyin: "xièxie", en: "thank you", level: "HSK1", ex: { hanzi: "謝謝你的幫忙。", pinyin: "Xièxie nǐ de bāng máng.", en: "Thanks for your help." } },
  { id: "v126", hanzi: "星期", pinyin: "xīngqī", en: "week", level: "HSK1", ex: { hanzi: "一個星期有七天。", pinyin: "Yī gè xīng qī yǒu qī tiān.", en: "A week has seven days." } },
  { id: "v127", hanzi: "學生", pinyin: "xuéshēng", en: "student", level: "HSK1", ex: { hanzi: "她是大學學生。", pinyin: "Tā shì dà xué xué shēng.", en: "She is a university student." } },
  { id: "v128", hanzi: "學習", pinyin: "xuéxí", en: "to study", level: "HSK1", ex: { hanzi: "我每天學習中文。", pinyin: "Wǒ měi tiān xué xí zhōng wén.", en: "I study Chinese every day." } },
  { id: "v129", hanzi: "學校", pinyin: "xuéxiào", en: "school", level: "HSK1", ex: { hanzi: "學校離這裡很近。", pinyin: "Xué xiào lí zhè lǐ hěn jìn.", en: "The school is close to here." } },
  { id: "v130", hanzi: "一", pinyin: "yī", en: "one", level: "HSK1", ex: { hanzi: "我有一個哥哥。", pinyin: "Wǒ yǒu yī gè gēge.", en: "I have one older brother." } },
  { id: "v131", hanzi: "一點兒", pinyin: "yìdiǎnr", en: "a little bit", level: "HSK1", ex: { hanzi: "我會說一點兒中文。", pinyin: "Wǒ huì shuō yìdiǎnr zhōng wén.", en: "I can speak a little Chinese." } },
  { id: "v132", hanzi: "醫生", pinyin: "yīshēng", en: "doctor", level: "HSK1", ex: { hanzi: "我爸爸是醫生。", pinyin: "Wǒ bàba shì yī shēng.", en: "My dad is a doctor." } },
  { id: "v133", hanzi: "醫院", pinyin: "yīyuàn", en: "hospital", level: "HSK1", ex: { hanzi: "醫院在銀行旁邊。", pinyin: "Yī yuàn zài yín xíng páng biān.", en: "The hospital is next to the bank." } },
  { id: "v134", hanzi: "衣服", pinyin: "yīfú", en: "clothes", level: "HSK1", ex: { hanzi: "這件衣服很漂亮。", pinyin: "Zhè jiàn yī fú hěn piàoliang.", en: "This piece of clothing is pretty." } },
  { id: "v135", hanzi: "椅子", pinyin: "yǐzi", en: "chair", level: "HSK1", ex: { hanzi: "請坐這個椅子。", pinyin: "Qǐng zuò zhè gè yǐ zi.", en: "Please sit in this chair." } },
  { id: "v136", hanzi: "有", pinyin: "yǒu", en: "to have / there is", level: "HSK1", ex: { hanzi: "我有一隻貓。", pinyin: "Wǒ yǒu yī zhǐ māo.", en: "I have a cat." } },
  { id: "v137", hanzi: "月", pinyin: "yuè", en: "month", level: "HSK1", ex: { hanzi: "我下個月去臺灣。", pinyin: "Wǒ xià gè yuè qù tái wān.", en: "I'm going to Taiwan next month." } },
  { id: "v138", hanzi: "再見", pinyin: "zàijiàn", en: "goodbye", level: "HSK1", ex: { hanzi: "明天見，再見！", pinyin: "Míng tiān jiàn zài jiàn!", en: "See you tomorrow, bye!" } },
  { id: "v139", hanzi: "在", pinyin: "zài", en: "at / in", level: "HSK1", ex: { hanzi: "我在家。", pinyin: "Wǒ zài jiā.", en: "I am at home." } },
  { id: "v140", hanzi: "怎麼", pinyin: "zěnme", en: "how", level: "HSK1", ex: { hanzi: "這個字怎麼念？", pinyin: "Zhè gè zì zěn me niàn?", en: "How is this character pronounced?" } },
  { id: "v141", hanzi: "怎麼樣", pinyin: "zěnmeyàng", en: "how about", level: "HSK1", ex: { hanzi: "這個怎麼樣？", pinyin: "Zhè gè zěn me yàng?", en: "How about this one?" } },
  { id: "v142", hanzi: "這", pinyin: "zhè", en: "this", level: "HSK1", ex: { hanzi: "這是誰的手機？", pinyin: "Zhè shì shéi de shǒu jī?", en: "Whose phone is this?" } },
  { id: "v143", hanzi: "中國", pinyin: "zhōngguó", en: "China", level: "HSK1", ex: { hanzi: "他來自中國。", pinyin: "Tā lái zì zhōng guó.", en: "He is from China." } },
  { id: "v144", hanzi: "中午", pinyin: "zhōngwǔ", en: "noon", level: "HSK1", ex: { hanzi: "中午我們吃飯。", pinyin: "Zhōng wǔ wǒ men chī fàn.", en: "We eat at noon." } },
  { id: "v145", hanzi: "住", pinyin: "zhù", en: "to live / reside", level: "HSK1", ex: { hanzi: "我住在臺北。", pinyin: "Wǒ zhù zài tái běi.", en: "I live in Taipei." } },
  { id: "v146", hanzi: "桌子", pinyin: "zhuōzi", en: "table / desk", level: "HSK1", ex: { hanzi: "杯子在桌子上。", pinyin: "Bēi zi zài zhuō zi shàng.", en: "The cup is on the table." } },
  { id: "v147", hanzi: "字", pinyin: "zì", en: "character / word", level: "HSK1", ex: { hanzi: "這個字怎麼念？", pinyin: "Zhè gè zì zěn me niàn?", en: "How is this character pronounced?" } },
  { id: "v148", hanzi: "昨天", pinyin: "zuótiān", en: "yesterday", level: "HSK1", ex: { hanzi: "昨天我很忙。", pinyin: "Zuó tiān wǒ hěn máng.", en: "I was busy yesterday." } },
  { id: "v149", hanzi: "做", pinyin: "zuò", en: "to do / make", level: "HSK1", ex: { hanzi: "你在做什麼？", pinyin: "Nǐ zài zuò shén me?", en: "What are you doing?" } },
  { id: "v150", hanzi: "坐", pinyin: "zuò", en: "to sit", level: "HSK1", ex: { hanzi: "請坐。", pinyin: "Qǐng zuò.", en: "Please sit." } },
  { id: "v151", hanzi: "吧", pinyin: "ba", en: "suggestion / softener particle", level: "HSK2", ex: { hanzi: "我們走吧。", pinyin: "Wǒ men zǒu ba.", en: "Let's go." } },
  { id: "v152", hanzi: "白", pinyin: "bái", en: "white", level: "HSK2", ex: { hanzi: "那隻貓是白的。", pinyin: "Nà zhǐ māo shì bái de.", en: "That cat is white." } },
  { id: "v153", hanzi: "百", pinyin: "bǎi", en: "hundred", level: "HSK2", ex: { hanzi: "這本書一百塊錢。", pinyin: "Zhè běn shū yī bǎi kuài qián.", en: "This book costs a hundred kuai." } },
  { id: "v154", hanzi: "幫助", pinyin: "bāngzhù", en: "to help", level: "HSK2", ex: { hanzi: "謝謝你幫助我。", pinyin: "Xièxie nǐ bāng zhù wǒ.", en: "Thanks for helping me." } },
  { id: "v155", hanzi: "報紙", pinyin: "bàozhǐ", en: "newspaper", level: "HSK2", ex: { hanzi: "爸爸在看報紙。", pinyin: "Bàba zài kàn bào zhǐ.", en: "Dad is reading the newspaper." } },
  { id: "v156", hanzi: "比", pinyin: "bǐ", en: "compared to", level: "HSK2", ex: { hanzi: "這個比那個大。", pinyin: "Zhè gè bǐ nà gè dà.", en: "This one is bigger than that one." } },
  { id: "v157", hanzi: "別", pinyin: "bié", en: "don't", level: "HSK2", ex: { hanzi: "別擔心。", pinyin: "Bié dān xīn.", en: "Don't worry." } },
  { id: "v158", hanzi: "賓館", pinyin: "bīnguǎn", en: "guesthouse / hotel", level: "HSK2", ex: { hanzi: "我們住在賓館。", pinyin: "Wǒ men zhù zài bīn guǎn.", en: "We're staying at a hotel." } },
  { id: "v159", hanzi: "長", pinyin: "cháng", en: "long", level: "HSK2", ex: { hanzi: "這條路很長。", pinyin: "Zhè tiáo lù hěn cháng.", en: "This road is long." } },
  { id: "v160", hanzi: "唱歌", pinyin: "chànggē", en: "to sing", level: "HSK2", ex: { hanzi: "她喜歡唱歌。", pinyin: "Tā xǐ huān chàng gē.", en: "She likes singing." } },
  { id: "v161", hanzi: "出", pinyin: "chū", en: "to go out / exit", level: "HSK2", ex: { hanzi: "他剛出去了。", pinyin: "Tā gāng chū qù le.", en: "He just went out." } },
  { id: "v162", hanzi: "穿", pinyin: "chuān", en: "to wear", level: "HSK2", ex: { hanzi: "她穿了一件新衣服。", pinyin: "Tā chuān le yī jiàn xīn yī fú.", en: "She's wearing a new piece of clothing." } },
  { id: "v163", hanzi: "次", pinyin: "cì", en: "(measure word for occurrences)", level: "HSK2", ex: { hanzi: "我去過一次臺灣。", pinyin: "Wǒ qù guo yī cì tái wān.", en: "I've been to Taiwan once." } },
  { id: "v164", hanzi: "從", pinyin: "cóng", en: "from", level: "HSK2", ex: { hanzi: "我從臺北來。", pinyin: "Wǒ cóng tái běi lái.", en: "I come from Taipei." } },
  { id: "v165", hanzi: "錯", pinyin: "cuò", en: "wrong / mistake", level: "HSK2", ex: { hanzi: "這個字寫錯了。", pinyin: "Zhè gè zì xiě cuò le.", en: "This character is written wrong." } },
  { id: "v166", hanzi: "打籃球", pinyin: "dǎlánqiú", en: "to play basketball", level: "HSK2", ex: { hanzi: "他喜歡打籃球。", pinyin: "Tā xǐ huān dǎ lán qiú.", en: "He likes playing basketball." } },
  { id: "v167", hanzi: "大家", pinyin: "dàjiā", en: "everyone", level: "HSK2", ex: { hanzi: "大家好！", pinyin: "Dà jiā hǎo!", en: "Hello everyone!" } },
  { id: "v168", hanzi: "到", pinyin: "dào", en: "to arrive / to", level: "HSK2", ex: { hanzi: "我們到家了。", pinyin: "Wǒ men dào jiā le.", en: "We've arrived home." } },
  { id: "v169", hanzi: "得", pinyin: "de", en: "structural particle (manner)", level: "HSK2", ex: { hanzi: "他說得很好。", pinyin: "Tā shuō de hěn hǎo.", en: "He speaks very well." } },
  { id: "v170", hanzi: "等", pinyin: "děng", en: "to wait", level: "HSK2", ex: { hanzi: "請等一下。", pinyin: "Qǐng děng yī xià.", en: "Please wait a moment." } },
  { id: "v171", hanzi: "弟弟", pinyin: "dìdi", en: "younger brother", level: "HSK2", ex: { hanzi: "我弟弟是學生。", pinyin: "Wǒ dì dì shì xué shēng.", en: "My younger brother is a student." } },
  { id: "v172", hanzi: "第一", pinyin: "dìyī", en: "first", level: "HSK2", ex: { hanzi: "這是我第一次來臺灣。", pinyin: "Zhè shì wǒ dì yī cì lái tái wān.", en: "This is my first time coming to Taiwan." } },
  { id: "v173", hanzi: "懂", pinyin: "dǒng", en: "to understand", level: "HSK2", ex: { hanzi: "我聽不懂。", pinyin: "Wǒ tīng bù dǒng.", en: "I don't understand." } },
  { id: "v174", hanzi: "對", pinyin: "duì", en: "right / correct; towards", level: "HSK2", ex: { hanzi: "你說得對。", pinyin: "Nǐ shuō de duì.", en: "You're right." } },
  { id: "v175", hanzi: "房間", pinyin: "fángjiān", en: "room", level: "HSK2", ex: { hanzi: "我的房間很小。", pinyin: "Wǒ de fáng jiān hěn xiǎo.", en: "My room is small." } },
  { id: "v176", hanzi: "非常", pinyin: "fēicháng", en: "very / extremely", level: "HSK2", ex: { hanzi: "這個電影非常好看。", pinyin: "Zhè gè diàn yǐng fēi cháng hǎo kàn.", en: "This movie is extremely good." } },
  { id: "v177", hanzi: "服務員", pinyin: "fúwùyuán", en: "waiter / waitress", level: "HSK2", ex: { hanzi: "服務員，請給我選單。", pinyin: "Fú wù yuán qǐng gěi wǒ cài dān.", en: "Waiter, please give me the menu." } },
  { id: "v178", hanzi: "高", pinyin: "gāo", en: "tall / high", level: "HSK2", ex: { hanzi: "他很高。", pinyin: "Tā hěn gāo.", en: "He is tall." } },
  { id: "v179", hanzi: "告訴", pinyin: "gàosu", en: "to tell", level: "HSK2", ex: { hanzi: "請告訴我你的名字。", pinyin: "Qǐng gàosu wǒ nǐ de míngzi.", en: "Please tell me your name." } },
  { id: "v180", hanzi: "哥哥", pinyin: "gēge", en: "older brother", level: "HSK2", ex: { hanzi: "他是我哥哥。", pinyin: "Tā shì wǒ gēge.", en: "He is my older brother." } },
  { id: "v181", hanzi: "給", pinyin: "gěi", en: "to give / for", level: "HSK2", ex: { hanzi: "請給我一杯水。", pinyin: "Qǐng gěi wǒ yī bēi shuǐ.", en: "Please give me a glass of water." } },
  { id: "v182", hanzi: "公共汽車", pinyin: "gōnggòngqìchē", en: "bus", level: "HSK2", ex: { hanzi: "我坐公共汽車去學校。", pinyin: "Wǒ zuò gōng gòng qì chē qù xué xiào.", en: "I take the bus to school." } },
  { id: "v183", hanzi: "公司", pinyin: "gōngsī", en: "company", level: "HSK2", ex: { hanzi: "他在一家公司工作。", pinyin: "Tā zài yī jiā gōng sī gōng zuò.", en: "He works at a company." } },
  { id: "v184", hanzi: "貴", pinyin: "guì", en: "expensive", level: "HSK2", ex: { hanzi: "這個手機很貴。", pinyin: "Zhè gè shǒu jī hěn guì.", en: "This phone is expensive." } },
  { id: "v185", hanzi: "過", pinyin: "guo", en: "experiential particle (have done)", level: "HSK2", ex: { hanzi: "我去過臺灣。", pinyin: "Wǒ qù guo tái wān.", en: "I have been to Taiwan." } },
  { id: "v186", hanzi: "孩子", pinyin: "háizi", en: "child", level: "HSK2", ex: { hanzi: "這個孩子很可愛。", pinyin: "Zhè gè hái zi hěn kě ài.", en: "This child is very cute." } },
  { id: "v187", hanzi: "還", pinyin: "hái", en: "still / also", level: "HSK2", ex: { hanzi: "他還在工作。", pinyin: "Tā hái zài gōng zuò.", en: "He is still working." } },
  { id: "v188", hanzi: "好吃", pinyin: "hǎochī", en: "tasty", level: "HSK2", ex: { hanzi: "這個菜很好吃。", pinyin: "Zhè gè cài hěn hǎo chī.", en: "This dish is delicious." } },
  { id: "v189", hanzi: "黑", pinyin: "hēi", en: "black", level: "HSK2", ex: { hanzi: "那隻貓是黑的。", pinyin: "Nà zhǐ māo shì hēi de.", en: "That cat is black." } },
  { id: "v190", hanzi: "紅", pinyin: "hóng", en: "red", level: "HSK2", ex: { hanzi: "她喜歡紅色。", pinyin: "Tā xǐ huān hóng sè.", en: "She likes red." } },
  { id: "v191", hanzi: "火車站", pinyin: "huǒchēzhàn", en: "train station", level: "HSK2", ex: { hanzi: "火車站在哪兒？", pinyin: "Huǒ chē zhàn zài nǎr?", en: "Where is the train station?" } },
  { id: "v192", hanzi: "機場", pinyin: "jīchǎng", en: "airport", level: "HSK2", ex: { hanzi: "我們去機場吧。", pinyin: "Wǒ men qù jī chǎng ba.", en: "Let's go to the airport." } },
  { id: "v193", hanzi: "雞蛋", pinyin: "jīdàn", en: "egg", level: "HSK2", ex: { hanzi: "我早上吃雞蛋。", pinyin: "Wǒ zǎo shàng chī jī dàn.", en: "I eat eggs in the morning." } },
  { id: "v194", hanzi: "件", pinyin: "jiàn", en: "(measure word for clothes/items)", level: "HSK2", ex: { hanzi: "我買了一件衣服。", pinyin: "Wǒ mǎi le yī jiàn yī fú.", en: "I bought a piece of clothing." } },
  { id: "v195", hanzi: "教室", pinyin: "jiàoshì", en: "classroom", level: "HSK2", ex: { hanzi: "老師在教室裡。", pinyin: "Lǎo shī zài jiào shì lǐ.", en: "The teacher is in the classroom." } },
  { id: "v196", hanzi: "姐姐", pinyin: "jiějie", en: "older sister", level: "HSK2", ex: { hanzi: "她是我姐姐。", pinyin: "Tā shì wǒ jiějie.", en: "She is my older sister." } },
  { id: "v197", hanzi: "介紹", pinyin: "jièshào", en: "to introduce", level: "HSK2", ex: { hanzi: "我來介紹一下。", pinyin: "Wǒ lái jiè shào yī xià.", en: "Let me introduce." } },
  { id: "v198", hanzi: "近", pinyin: "jìn", en: "close / near", level: "HSK2", ex: { hanzi: "學校離我家很近。", pinyin: "Xué xiào lí wǒ jiā hěn jìn.", en: "The school is close to my house." } },
  { id: "v199", hanzi: "進", pinyin: "jìn", en: "to enter", level: "HSK2", ex: { hanzi: "請進。", pinyin: "Qǐng jìn.", en: "Please come in." } },
  { id: "v200", hanzi: "就", pinyin: "jiù", en: "then / just (emphasis)", level: "HSK2", ex: { hanzi: "我馬上就到。", pinyin: "Wǒ mǎ shàng jiù dào.", en: "I'll arrive right away." } },
  { id: "v201", hanzi: "覺得", pinyin: "juéde", en: "to feel / think", level: "HSK2", ex: { hanzi: "我覺得這個很好。", pinyin: "Wǒ jué de zhè gè hěn hǎo.", en: "I think this is good." } },
  { id: "v202", hanzi: "咖啡", pinyin: "kāfēi", en: "coffee", level: "HSK2", ex: { hanzi: "我每天喝咖啡。", pinyin: "Wǒ měi tiān hē kā fēi.", en: "I drink coffee every day." } },
  { id: "v203", hanzi: "開始", pinyin: "kāishǐ", en: "to begin", level: "HSK2", ex: { hanzi: "電影開始了。", pinyin: "Diàn yǐng kāi shǐ le.", en: "The movie has begun." } },
  { id: "v204", hanzi: "考試", pinyin: "kǎoshì", en: "exam", level: "HSK2", ex: { hanzi: "我明天有考試。", pinyin: "Wǒ míng tiān yǒu kǎo shì.", en: "I have an exam tomorrow." } },
  { id: "v205", hanzi: "可能", pinyin: "kěnéng", en: "maybe / possible", level: "HSK2", ex: { hanzi: "他可能不來了。", pinyin: "Tā kě néng bù lái le.", en: "He might not come." } },
  { id: "v206", hanzi: "可以", pinyin: "kěyǐ", en: "can / may", level: "HSK2", ex: { hanzi: "你可以進來。", pinyin: "Nǐ kě yǐ jìn lái.", en: "You may come in." } },
  { id: "v207", hanzi: "課", pinyin: "kè", en: "class / lesson", level: "HSK2", ex: { hanzi: "我們的課很有意思。", pinyin: "Wǒ men de kè hěn yǒu yì sī.", en: "Our class is very interesting." } },
  { id: "v208", hanzi: "快", pinyin: "kuài", en: "fast", level: "HSK2", ex: { hanzi: "你走得很快。", pinyin: "Nǐ zǒu de hěn kuài.", en: "You walk very fast." } },
  { id: "v209", hanzi: "快樂", pinyin: "kuàilè", en: "happy", level: "HSK2", ex: { hanzi: "生日快樂！", pinyin: "Shēng rì kuài lè!", en: "Happy birthday!" } },
  { id: "v210", hanzi: "累", pinyin: "lèi", en: "tired", level: "HSK2", ex: { hanzi: "我今天很累。", pinyin: "Wǒ jīn tiān hěn lèi.", en: "I'm tired today." } },
  { id: "v211", hanzi: "離", pinyin: "lí", en: "from (distance)", level: "HSK2", ex: { hanzi: "學校離我家很遠。", pinyin: "Xué xiào lí wǒ jiā hěn yuǎn.", en: "The school is far from my house." } },
  { id: "v212", hanzi: "兩", pinyin: "liǎng", en: "two (with measure words)", level: "HSK2", ex: { hanzi: "我有兩個哥哥。", pinyin: "Wǒ yǒu liǎng gè gēge.", en: "I have two older brothers." } },
  { id: "v213", hanzi: "零", pinyin: "líng", en: "zero", level: "HSK2", ex: { hanzi: "我的電話號碼有一個零。", pinyin: "Wǒ de diàn huà hào mǎ yǒu yī gè líng.", en: "My phone number has a zero." } },
  { id: "v214", hanzi: "路", pinyin: "lù", en: "road", level: "HSK2", ex: { hanzi: "去學校的路很近。", pinyin: "Qù xué xiào de lù hěn jìn.", en: "The road to school is close." } },
  { id: "v215", hanzi: "旅遊", pinyin: "lǚyóu", en: "to travel", level: "HSK2", ex: { hanzi: "我喜歡去臺灣旅遊。", pinyin: "Wǒ xǐ huān qù tái wān lǚ yóu.", en: "I like traveling to Taiwan." } },
  { id: "v216", hanzi: "賣", pinyin: "mài", en: "to sell", level: "HSK2", ex: { hanzi: "這家商店賣水果。", pinyin: "Zhè jiā shāng diàn mài shuǐ guǒ.", en: "This store sells fruit." } },
  { id: "v217", hanzi: "慢", pinyin: "màn", en: "slow", level: "HSK2", ex: { hanzi: "他走得很慢。", pinyin: "Tā zǒu de hěn màn.", en: "He walks slowly." } },
  { id: "v218", hanzi: "忙", pinyin: "máng", en: "busy", level: "HSK2", ex: { hanzi: "他的工作很忙。", pinyin: "Tā de gōng zuò hěn máng.", en: "His job is very busy." } },
  { id: "v219", hanzi: "每", pinyin: "měi", en: "every", level: "HSK2", ex: { hanzi: "我每天學習中文。", pinyin: "Wǒ měi tiān xué xí zhōng wén.", en: "I study Chinese every day." } },
  { id: "v220", hanzi: "妹妹", pinyin: "mèimei", en: "younger sister", level: "HSK2", ex: { hanzi: "我妹妹很漂亮。", pinyin: "Wǒ mèimei hěn piàoliang.", en: "My younger sister is pretty." } },
  { id: "v221", hanzi: "門", pinyin: "mén", en: "door / gate", level: "HSK2", ex: { hanzi: "門是開的。", pinyin: "Mén shì kāi de.", en: "The door is open." } },
  { id: "v222", hanzi: "麵條", pinyin: "miàntiáo", en: "noodles", level: "HSK2", ex: { hanzi: "我想吃麵條。", pinyin: "Wǒ xiǎng chī miàn tiáo.", en: "I want to eat noodles." } },
  { id: "v223", hanzi: "男", pinyin: "nán", en: "male", level: "HSK2", ex: { hanzi: "他是男學生。", pinyin: "Tā shì nán xué shēng.", en: "He is a male student." } },
  { id: "v224", hanzi: "您", pinyin: "nín", en: "you (polite)", level: "HSK2", ex: { hanzi: "您好，很高興認識您。", pinyin: "Nín hǎo hěn gāo xīng rènshi nín.", en: "Hello, nice to meet you." } },
  { id: "v225", hanzi: "牛奶", pinyin: "niúnǎi", en: "milk", level: "HSK2", ex: { hanzi: "我早上喝牛奶。", pinyin: "Wǒ zǎo shàng hē niú nǎi.", en: "I drink milk in the morning." } },
  { id: "v226", hanzi: "女", pinyin: "nǚ", en: "female", level: "HSK2", ex: { hanzi: "她是女老師。", pinyin: "Tā shì nǚ lǎo shī.", en: "She is a female teacher." } },
  { id: "v227", hanzi: "旁邊", pinyin: "pángbiān", en: "beside / next to", level: "HSK2", ex: { hanzi: "銀行在商店旁邊。", pinyin: "Yín xíng zài shāng diàn páng biān.", en: "The bank is next to the store." } },
  { id: "v228", hanzi: "跑步", pinyin: "pǎobù", en: "to run / jog", level: "HSK2", ex: { hanzi: "我每天跑步。", pinyin: "Wǒ měi tiān pǎo bù.", en: "I run every day." } },
  { id: "v229", hanzi: "便宜", pinyin: "piányi", en: "cheap", level: "HSK2", ex: { hanzi: "這個很便宜。", pinyin: "Zhè gè hěn biàn yí.", en: "This is cheap." } },
  { id: "v230", hanzi: "票", pinyin: "piào", en: "ticket", level: "HSK2", ex: { hanzi: "我買了兩張票。", pinyin: "Wǒ mǎi le liǎng zhāng piào.", en: "I bought two tickets." } },
  { id: "v231", hanzi: "妻子", pinyin: "qīzi", en: "wife", level: "HSK2", ex: { hanzi: "他的妻子是老師。", pinyin: "Tā de qīzi shì lǎo shī.", en: "His wife is a teacher." } },
  { id: "v232", hanzi: "起床", pinyin: "qǐchuáng", en: "to get up", level: "HSK2", ex: { hanzi: "我七點起床。", pinyin: "Wǒ qī diǎn qǐ chuáng.", en: "I get up at seven." } },
  { id: "v233", hanzi: "千", pinyin: "qiān", en: "thousand", level: "HSK2", ex: { hanzi: "這個手機三千塊錢。", pinyin: "Zhè gè shǒu jī sān qiān kuài qián.", en: "This phone costs three thousand kuai." } },
  { id: "v234", hanzi: "鉛筆", pinyin: "qiānbǐ", en: "pencil", level: "HSK2", ex: { hanzi: "請給我一支鉛筆。", pinyin: "Qǐng gěi wǒ yī zhī qiān bǐ.", en: "Please give me a pencil." } },
  { id: "v235", hanzi: "晴", pinyin: "qíng", en: "sunny / clear", level: "HSK2", ex: { hanzi: "今天是晴天。", pinyin: "Jīn tiān shì qíng tiān.", en: "Today is a sunny day." } },
  { id: "v236", hanzi: "去年", pinyin: "qùnián", en: "last year", level: "HSK2", ex: { hanzi: "我去年去了臺灣。", pinyin: "Wǒ qù nián qù le tái wān.", en: "I went to Taiwan last year." } },
  { id: "v237", hanzi: "讓", pinyin: "ràng", en: "to let / allow", level: "HSK2", ex: { hanzi: "媽媽讓我回家。", pinyin: "Māma ràng wǒ huí jiā.", en: "Mom let me go home." } },
  { id: "v238", hanzi: "日", pinyin: "rì", en: "day / sun", level: "HSK2", ex: { hanzi: "今天是幾月幾日？", pinyin: "Jīn tiān shì jǐ yuè jǐ rì?", en: "What is today's date?" } },
  { id: "v239", hanzi: "上班", pinyin: "shàngbān", en: "to go to work", level: "HSK2", ex: { hanzi: "我每天上班。", pinyin: "Wǒ měi tiān shàng bān.", en: "I go to work every day." } },
  { id: "v240", hanzi: "身體", pinyin: "shēntǐ", en: "body / health", level: "HSK2", ex: { hanzi: "你的身體好嗎？", pinyin: "Nǐ de shēn tǐ hǎo ma?", en: "Are you in good health?" } },
  { id: "v241", hanzi: "生病", pinyin: "shēngbìng", en: "to get sick", level: "HSK2", ex: { hanzi: "他生病了。", pinyin: "Tā shēng bìng le.", en: "He got sick." } },
  { id: "v242", hanzi: "生日", pinyin: "shēngrì", en: "birthday", level: "HSK2", ex: { hanzi: "祝你生日快樂！", pinyin: "Zhù nǐ shēng rì kuài lè!", en: "Happy birthday to you!" } },
  { id: "v243", hanzi: "時間", pinyin: "shíjiān", en: "time", level: "HSK2", ex: { hanzi: "我沒有時間。", pinyin: "Wǒ méi yǒu shí jiān.", en: "I don't have time." } },
  { id: "v244", hanzi: "事情", pinyin: "shìqing", en: "matter / thing", level: "HSK2", ex: { hanzi: "我有一件事情要說。", pinyin: "Wǒ yǒu yī jiàn shìqing yào shuō.", en: "I have a matter to discuss." } },
  { id: "v245", hanzi: "手錶", pinyin: "shǒubiǎo", en: "wristwatch", level: "HSK2", ex: { hanzi: "這個手錶很貴。", pinyin: "Zhè gè shǒu biǎo hěn guì.", en: "This watch is expensive." } },
  { id: "v246", hanzi: "手機", pinyin: "shǒujī", en: "cellphone", level: "HSK2", ex: { hanzi: "我的手機在桌上。", pinyin: "Wǒ de shǒu jī zài zhuō shàng.", en: "My phone is on the table." } },
  { id: "v247", hanzi: "說話", pinyin: "shuōhuà", en: "to speak / talk", level: "HSK2", ex: { hanzi: "請別說話。", pinyin: "Qǐng bié shuō huà.", en: "Please don't talk." } },
  { id: "v248", hanzi: "送", pinyin: "sòng", en: "to give (as gift) / see off", level: "HSK2", ex: { hanzi: "我送你一本書。", pinyin: "Wǒ sòng nǐ yī běn shū.", en: "I'll give you a book." } },
  { id: "v249", hanzi: "雖然…但是…", pinyin: "suīrán…dànshì…", en: "although… but…", level: "HSK2", ex: { hanzi: "雖然很貴，但是很好吃。", pinyin: "Suī rán hěn guì dàn shì hěn hǎo chī.", en: "Although it's expensive, it's delicious." } },
  { id: "v250", hanzi: "它", pinyin: "tā", en: "it", level: "HSK2", ex: { hanzi: "這是我的狗，它很可愛。", pinyin: "Zhè shì wǒ de gǒu tā hěn kě ài.", en: "This is my dog, it's very cute." } },
  { id: "v251", hanzi: "踢足球", pinyin: "tīzúqiú", en: "to play soccer", level: "HSK2", ex: { hanzi: "他喜歡踢足球。", pinyin: "Tā xǐ huān tī zú qiú.", en: "He likes playing soccer." } },
  { id: "v252", hanzi: "題", pinyin: "tí", en: "question / topic (exam)", level: "HSK2", ex: { hanzi: "這個題很難。", pinyin: "Zhè gè tí hěn nán.", en: "This question is difficult." } },
  { id: "v253", hanzi: "跳舞", pinyin: "tiàowǔ", en: "to dance", level: "HSK2", ex: { hanzi: "她喜歡跳舞。", pinyin: "Tā xǐ huān tiào wǔ.", en: "She likes dancing." } },
  { id: "v254", hanzi: "外", pinyin: "wài", en: "outside", level: "HSK2", ex: { hanzi: "貓在外面。", pinyin: "Māo zài wài miàn.", en: "The cat is outside." } },
  { id: "v255", hanzi: "完", pinyin: "wán", en: "to finish", level: "HSK2", ex: { hanzi: "我吃完了。", pinyin: "Wǒ chī wán le.", en: "I've finished eating." } },
  { id: "v256", hanzi: "玩", pinyin: "wán", en: "to play", level: "HSK2", ex: { hanzi: "孩子在玩。", pinyin: "Hái zi zài wán.", en: "The child is playing." } },
  { id: "v257", hanzi: "晚上", pinyin: "wǎnshàng", en: "evening", level: "HSK2", ex: { hanzi: "晚上我在家。", pinyin: "Wǎn shàng wǒ zài jiā.", en: "I'm at home in the evening." } },
  { id: "v258", hanzi: "往", pinyin: "wǎng", en: "towards", level: "HSK2", ex: { hanzi: "往前走。", pinyin: "Wǎng qián zǒu.", en: "Walk forward." } },
  { id: "v259", hanzi: "為什麼", pinyin: "wèishénme", en: "why", level: "HSK2", ex: { hanzi: "你為什麼不來？", pinyin: "Nǐ wèi shén me bù lái?", en: "Why aren't you coming?" } },
  { id: "v260", hanzi: "問", pinyin: "wèn", en: "to ask", level: "HSK2", ex: { hanzi: "我想問一個問題。", pinyin: "Wǒ xiǎng wèn yī gè wèn tí.", en: "I want to ask a question." } },
  { id: "v261", hanzi: "問題", pinyin: "wèntí", en: "question / problem", level: "HSK2", ex: { hanzi: "這是一個好問題。", pinyin: "Zhè shì yī gè hǎo wèn tí.", en: "This is a good question." } },
  { id: "v262", hanzi: "希望", pinyin: "xīwàng", en: "to hope", level: "HSK2", ex: { hanzi: "我希望你喜歡。", pinyin: "Wǒ xī wàng nǐ xǐ huān.", en: "I hope you like it." } },
  { id: "v263", hanzi: "西瓜", pinyin: "xīguā", en: "watermelon", level: "HSK2", ex: { hanzi: "夏天我喜歡吃西瓜。", pinyin: "Xià tiān wǒ xǐ huān chī xī guā.", en: "In summer I like eating watermelon." } },
  { id: "v264", hanzi: "洗", pinyin: "xǐ", en: "to wash", level: "HSK2", ex: { hanzi: "我要洗衣服。", pinyin: "Wǒ yào xǐ yī fú.", en: "I need to wash clothes." } },
  { id: "v265", hanzi: "小時", pinyin: "xiǎoshí", en: "hour", level: "HSK2", ex: { hanzi: "我等了一個小時。", pinyin: "Wǒ děng le yī gè xiǎo shí.", en: "I waited for one hour." } },
  { id: "v266", hanzi: "笑", pinyin: "xiào", en: "to laugh / smile", level: "HSK2", ex: { hanzi: "她笑了。", pinyin: "Tā xiào le.", en: "She smiled." } },
  { id: "v267", hanzi: "新", pinyin: "xīn", en: "new", level: "HSK2", ex: { hanzi: "這是我的新手機。", pinyin: "Zhè shì wǒ de xīn shǒu jī.", en: "This is my new phone." } },
  { id: "v268", hanzi: "姓", pinyin: "xìng", en: "surname", level: "HSK2", ex: { hanzi: "你姓什麼？", pinyin: "Nǐ xìng shén me?", en: "What is your surname?" } },
  { id: "v269", hanzi: "休息", pinyin: "xiūxi", en: "to rest", level: "HSK2", ex: { hanzi: "我需要休息。", pinyin: "Wǒ xū yào xiūxi.", en: "I need to rest." } },
  { id: "v270", hanzi: "雪", pinyin: "xuě", en: "snow", level: "HSK2", ex: { hanzi: "臺北很少下雪。", pinyin: "Tái běi hěn shǎo xià xuě.", en: "It rarely snows in Taipei." } },
  { id: "v271", hanzi: "顏色", pinyin: "yánsè", en: "color", level: "HSK2", ex: { hanzi: "你喜歡什麼顏色？", pinyin: "Nǐ xǐ huān shén me yán sè?", en: "What color do you like?" } },
  { id: "v272", hanzi: "眼睛", pinyin: "yǎnjīng", en: "eye", level: "HSK2", ex: { hanzi: "她的眼睛很漂亮。", pinyin: "Tā de yǎn jīng hěn piàoliang.", en: "Her eyes are very pretty." } },
  { id: "v273", hanzi: "羊肉", pinyin: "yángròu", en: "mutton", level: "HSK2", ex: { hanzi: "我不吃羊肉。", pinyin: "Wǒ bù chī yáng ròu.", en: "I don't eat mutton." } },
  { id: "v274", hanzi: "藥", pinyin: "yào", en: "medicine", level: "HSK2", ex: { hanzi: "我要吃藥。", pinyin: "Wǒ yào chī yào.", en: "I need to take medicine." } },
  { id: "v275", hanzi: "要", pinyin: "yào", en: "to want / will", level: "HSK2", ex: { hanzi: "我要買一本書。", pinyin: "Wǒ yào mǎi yī běn shū.", en: "I want to buy a book." } },
  { id: "v276", hanzi: "也", pinyin: "yě", en: "also", level: "HSK2", ex: { hanzi: "我也是學生。", pinyin: "Wǒ yě shì xué shēng.", en: "I'm also a student." } },
  { id: "v277", hanzi: "一下", pinyin: "yīxià", en: "(softens a verb) a bit", level: "HSK2", ex: { hanzi: "請等一下。", pinyin: "Qǐng děng yī xià.", en: "Please wait a moment." } },
  { id: "v278", hanzi: "已經", pinyin: "yǐjīng", en: "already", level: "HSK2", ex: { hanzi: "他已經走了。", pinyin: "Tā yǐ jīng zǒu le.", en: "He has already left." } },
  { id: "v279", hanzi: "一起", pinyin: "yìqǐ", en: "together", level: "HSK2", ex: { hanzi: "我們一起去吧。", pinyin: "Wǒ men yī qǐ qù ba.", en: "Let's go together." } },
  { id: "v280", hanzi: "意思", pinyin: "yìsi", en: "meaning", level: "HSK2", ex: { hanzi: "這個字是什麼意思？", pinyin: "Zhè gè zì shì shén me yì sī?", en: "What does this character mean?" } },
  { id: "v281", hanzi: "因為…所以…", pinyin: "yīnwèi…suǒyǐ…", en: "because… so…", level: "HSK2", ex: { hanzi: "因為下雨，所以我在家。", pinyin: "Yīn wèi xià yǔ suǒ yǐ wǒ zài jiā.", en: "Because it's raining, I'm staying home." } },
  { id: "v282", hanzi: "陰", pinyin: "yīn", en: "overcast / cloudy", level: "HSK2", ex: { hanzi: "今天是陰天。", pinyin: "Jīn tiān shì yīn tiān.", en: "Today is overcast." } },
  { id: "v283", hanzi: "游泳", pinyin: "yóuyǒng", en: "to swim", level: "HSK2", ex: { hanzi: "我喜歡游泳。", pinyin: "Wǒ xǐ huān yóu yǒng.", en: "I like swimming." } },
  { id: "v284", hanzi: "右邊", pinyin: "yòubiān", en: "right side", level: "HSK2", ex: { hanzi: "銀行在右邊。", pinyin: "Yín xíng zài yòu biān.", en: "The bank is on the right." } },
  { id: "v285", hanzi: "魚", pinyin: "yú", en: "fish", level: "HSK2", ex: { hanzi: "我不喜歡吃魚。", pinyin: "Wǒ bù xǐ huān chī yú.", en: "I don't like eating fish." } },
  { id: "v286", hanzi: "遠", pinyin: "yuǎn", en: "far", level: "HSK2", ex: { hanzi: "學校離我家很遠。", pinyin: "Xué xiào lí wǒ jiā hěn yuǎn.", en: "The school is far from my house." } },
  { id: "v287", hanzi: "運動", pinyin: "yùndòng", en: "sports / to exercise", level: "HSK2", ex: { hanzi: "我每天運動。", pinyin: "Wǒ měi tiān yùn dòng.", en: "I exercise every day." } },
  { id: "v288", hanzi: "再", pinyin: "zài", en: "again", level: "HSK2", ex: { hanzi: "請再說一次。", pinyin: "Qǐng zài shuō yī cì.", en: "Please say it again." } },
  { id: "v289", hanzi: "早上", pinyin: "zǎoshàng", en: "early morning", level: "HSK2", ex: { hanzi: "早上好！", pinyin: "Zǎo shàng hǎo!", en: "Good morning!" } },
  { id: "v290", hanzi: "丈夫", pinyin: "zhàngfū", en: "husband", level: "HSK2", ex: { hanzi: "她的丈夫是醫生。", pinyin: "Tā de zhàng fū shì yī shēng.", en: "Her husband is a doctor." } },
  { id: "v291", hanzi: "找", pinyin: "zhǎo", en: "to look for", level: "HSK2", ex: { hanzi: "你在找什麼？", pinyin: "Nǐ zài zhǎo shén me?", en: "What are you looking for?" } },
  { id: "v292", hanzi: "著", pinyin: "zhe", en: "continuous-state particle", level: "HSK2", ex: { hanzi: "她笑著說。", pinyin: "Tā xiào zhe shuō.", en: "She said it while smiling." } },
  { id: "v293", hanzi: "真", pinyin: "zhēn", en: "really / truly", level: "HSK2", ex: { hanzi: "這個真好吃。", pinyin: "Zhè gè zhēn hǎo chī.", en: "This is really delicious." } },
  { id: "v294", hanzi: "正在", pinyin: "zhèngzài", en: "in the process of", level: "HSK2", ex: { hanzi: "我正在吃飯。", pinyin: "Wǒ zhèng zài chī fàn.", en: "I am eating right now." } },
  { id: "v295", hanzi: "知道", pinyin: "zhīdào", en: "to know", level: "HSK2", ex: { hanzi: "我不知道。", pinyin: "Wǒ bù zhī dào.", en: "I don't know." } },
  { id: "v296", hanzi: "準備", pinyin: "zhǔnbèi", en: "to prepare", level: "HSK2", ex: { hanzi: "我在準備考試。", pinyin: "Wǒ zài zhǔn bèi kǎo shì.", en: "I'm preparing for the exam." } },
  { id: "v297", hanzi: "走", pinyin: "zǒu", en: "to walk / leave", level: "HSK2", ex: { hanzi: "我們走吧。", pinyin: "Wǒ men zǒu ba.", en: "Let's go." } },
  { id: "v298", hanzi: "最", pinyin: "zuì", en: "most", level: "HSK2", ex: { hanzi: "他是最高的。", pinyin: "Tā shì zuì gāo de.", en: "He is the tallest." } },
  { id: "v299", hanzi: "左邊", pinyin: "zuǒbiān", en: "left side", level: "HSK2", ex: { hanzi: "商店在左邊。", pinyin: "Shāng diàn zài zuǒ biān.", en: "The store is on the left." } },
];

const GRAMMAR = [
  {
    id: "g1",
    title: "是 — identity sentences",
    explain: "Subject + 是 + Noun states what something is. Negate with 不是.",
    examples: [
      { hanzi: "我是學生。", pinyin: "Wǒ shì xué shēng.", en: "I am a student." },
      { hanzi: "他不是老師。", pinyin: "Tā bù shì lǎo shī.", en: "He is not a teacher." }
    ],
  },
  {
    id: "g2",
    title: "的 — possession",
    explain: "Noun/pronoun + 的 + Noun shows possession, like 's in English.",
    examples: [
      { hanzi: "這是我的書。", pinyin: "Zhè shì wǒ de shū.", en: "This is my book." },
      { hanzi: "老師的手機在桌上。", pinyin: "Lǎo shī de shǒu jī zài zhuō shàng.", en: "The teacher's phone is on the table." }
    ],
  },
  {
    id: "g3",
    title: "有 / 沒有 — existence & possession",
    explain: "有 means 'to have' or 'there is'. Negate with 沒有, not 不有.",
    examples: [
      { hanzi: "我有一隻貓。", pinyin: "Wǒ yǒu yī zhǐ māo.", en: "I have a cat." },
      { hanzi: "我沒有錢。", pinyin: "Wǒ méi yǒu qián.", en: "I don't have money." }
    ],
  },
  {
    id: "g4",
    title: "嗎 — yes/no questions",
    explain: "Add 嗎 to the end of a statement to turn it into a yes/no question.",
    examples: [
      { hanzi: "你是學生嗎？", pinyin: "Nǐ shì xué shēng ma?", en: "Are you a student?" },
      { hanzi: "你喜歡喝茶嗎？", pinyin: "Nǐ xǐ huān hē chá ma?", en: "Do you like drinking tea?" }
    ],
  },
  {
    id: "g5",
    title: "Question words — 什麼 / 誰 / 哪裡 / 怎麼",
    explain: "Question words sit right where the answer would go — no word-order flip like in English.",
    examples: [
      { hanzi: "你叫什麼名字？", pinyin: "Nǐ jiào shén me míngzi?", en: "What is your name?" },
      { hanzi: "你住在哪裡？", pinyin: "Nǐ zhù zài nǎ lǐ?", en: "Where do you live?" }
    ],
  },
  {
    id: "g6",
    title: "在 — location",
    explain: "在 + place marks where someone or something is, or where an action happens.",
    examples: [
      { hanzi: "我在家。", pinyin: "Wǒ zài jiā.", en: "I am at home." },
      { hanzi: "我在學校學中文。", pinyin: "Wǒ zài xué xiào xué zhōng wén.", en: "I study Chinese at school." }
    ],
  },
  {
    id: "g7",
    title: "了 — completed action",
    explain: "了 after a verb marks that the action happened or is finished.",
    examples: [
      { hanzi: "我吃了。", pinyin: "Wǒ chī le.", en: "I've eaten." },
      { hanzi: "他去了臺北。", pinyin: "Tā qù le tái běi.", en: "He went to Taipei." }
    ],
  },
  {
    id: "g8",
    title: "Time + Place + Verb order",
    explain: "Mandarin word order is Subject + Time + Place + Verb — the opposite tail-order from English.",
    examples: [
      { hanzi: "我今天在家看書。", pinyin: "Wǒ jīn tiān zài jiā kàn shū.", en: "I'm reading at home today." }
    ],
  },
  {
    id: "g9",
    title: "想 / 要 — wanting to do something",
    explain: "想 (would like to) is softer than 要 (want to / will). Both go before a verb.",
    examples: [
      { hanzi: "我想去臺灣。", pinyin: "Wǒ xiǎng qù tái wān.", en: "I'd like to go to Taiwan." },
      { hanzi: "我要買一本書。", pinyin: "Wǒ yào mǎi yī běn shū.", en: "I want to buy a book." }
    ],
  },
  {
    id: "g10",
    title: "比 — comparisons",
    explain: "A + 比 + B + adjective means 'A is more [adjective] than B'.",
    examples: [
      { hanzi: "這個比那個大。", pinyin: "Zhè gè bǐ nà gè dà.", en: "This one is bigger than that one." }
    ],
  },
  {
    id: "g11",
    title: "因為...所以... — because / so",
    explain: "因為 introduces the reason, 所以 introduces the result — often both appear in the same sentence.",
    examples: [
      { hanzi: "因為下雨，所以我在家。", pinyin: "Yīn wèi xià yǔ suǒ yǐ wǒ zài jiā.", en: "Because it's raining, I'm staying home." }
    ],
  },
  {
    id: "g12",
    title: "可以 / 會 / 能 — three flavors of 'can'",
    explain: "可以 = allowed to; 會 = know how to (learned skill); 能 = physically/practically able to.",
    examples: [
      { hanzi: "你可以進來。", pinyin: "Nǐ kě yǐ jìn lái.", en: "You may come in." },
      { hanzi: "我會說中文。", pinyin: "Wǒ huì shuō zhōng wén.", en: "I can speak Chinese." }
    ],
  },
  {
    id: "g13",
    title: "雖然...但是... — although / but",
    explain: "Pairs a concession with a contrast — 雖然 introduces the acknowledged fact, 但是 introduces what happens anyway.",
    examples: [
      { hanzi: "雖然很貴，但是很好吃。", pinyin: "Suī rán hěn guì dàn shì hěn hǎo chī.", en: "Although it's expensive, it's delicious." }
    ],
  },
  {
    id: "g14",
    title: "一下 — softening a verb",
    explain: "一下 after a verb makes it feel brief, casual, or polite — 'just do X for a bit'.",
    examples: [
      { hanzi: "請等一下。", pinyin: "Qǐng děng yī xià.", en: "Please wait a moment." },
      { hanzi: "我來介紹一下。", pinyin: "Wǒ lái jiè shào yī xià.", en: "Let me introduce [this]." }
    ],
  },
  {
    id: "g15",
    title: "正在 / 在 + Verb — happening right now",
    explain: "正在 (or just 在) before a verb marks an action in progress, like English '-ing'.",
    examples: [
      { hanzi: "我正在吃飯。", pinyin: "Wǒ zhèng zài chī fàn.", en: "I am eating right now." },
      { hanzi: "他正在工作。", pinyin: "Tā zhèng zài gōng zuò.", en: "He is working right now." }
    ],
  },
  {
    id: "g16",
    title: "著 — an ongoing state",
    explain: "著 attached to a verb shows a state continuing to hold, often while something else happens.",
    examples: [
      { hanzi: "她笑著說。", pinyin: "Tā xiào zhe shuō.", en: "She said it while smiling." },
      { hanzi: "門開著。", pinyin: "Mén kāi zhe.", en: "The door is open (and staying open)." }
    ],
  },
  {
    id: "g17",
    title: "過 — have you ever...",
    explain: "過 after a verb marks experience — that something has happened at least once before.",
    examples: [
      { hanzi: "我去過臺灣。", pinyin: "Wǒ qù guo tái wān.", en: "I have been to Taiwan." },
      { hanzi: "你看過這部電影嗎？", pinyin: "Nǐ kàn guo zhè bù diàn yǐng ma?", en: "Have you seen this movie?" }
    ],
  },
  {
    id: "g18",
    title: "得 — describing how an action goes",
    explain: "Verb + 得 + Adjective comments on the manner or degree of an action.",
    examples: [
      { hanzi: "他說得很好。", pinyin: "Tā shuō de hěn hǎo.", en: "He speaks very well." },
      { hanzi: "你走得很快。", pinyin: "Nǐ zǒu de hěn kuài.", en: "You walk very fast." }
    ],
  },
  {
    id: "g19",
    title: "從...到... — from...to...",
    explain: "從 marks the starting point, 到 marks the destination — for places or times.",
    examples: [
      { hanzi: "我們從臺北坐車到臺中。", pinyin: "Wǒ men cóng tái běi zuò chē dào tái zhōng.", en: "We're taking a ride from Taipei to Taichung." }
    ],
  },
  {
    id: "g20",
    title: "太...了 — too much of something",
    explain: "太 before an adjective, closed off with 了, expresses 'too X'.",
    examples: [
      { hanzi: "這個太貴了。", pinyin: "Zhè gè tài guì le.", en: "This is too expensive." },
      { hanzi: "天氣太熱了。", pinyin: "Tiān qì tài rè le.", en: "The weather is too hot." }
    ],
  },
  {
    id: "g21",
    title: "一點兒 — a little",
    explain: "一點兒 softens an adjective or a request — 'a bit' of something.",
    examples: [
      { hanzi: "這個比那個好一點兒。", pinyin: "Zhè gè bǐ nà gè hǎo yìdiǎnr.", en: "This one is a little better than that one." },
      { hanzi: "我想喝一點兒水。", pinyin: "Wǒ xiǎng hē yìdiǎnr shuǐ.", en: "I'd like a little water." }
    ],
  },
  {
    id: "g22",
    title: "Position words — 裡 / 上 / 前面 / 旁邊...",
    explain: "在 + place + a position word (裡 inside, 上 on top, 前面 in front, 旁邊 next to...) pins down exactly where.",
    examples: [
      { hanzi: "錢在包裡。", pinyin: "Qián zài bāo lǐ.", en: "The money is in the bag." },
      { hanzi: "銀行在商店旁邊。", pinyin: "Yín xíng zài shāng diàn páng biān.", en: "The bank is next to the store." }
    ],
  },
  {
    id: "g23",
    title: "要...了 — about to happen",
    explain: "要 (or 快要) with 了 at the end of the sentence signals something is about to occur.",
    examples: [
      { hanzi: "要下雨了。", pinyin: "Yào xià yǔ le.", en: "It's about to rain." },
      { hanzi: "電影要開始了。", pinyin: "Diàn yǐng yào kāi shǐ le.", en: "The movie is about to start." }
    ],
  },
  {
    id: "g24",
    title: "多 + Adjective — asking 'how ___'",
    explain: "多 before certain adjectives (大, 高, 長, 久) forms questions about degree or extent.",
    examples: [
      { hanzi: "你今年多大？", pinyin: "Nǐ jīn nián duō dà?", en: "How old are you this year?" },
      { hanzi: "這條路多長？", pinyin: "Zhè tiáo lù duō cháng?", en: "How long is this road?" }
    ],
  },
];

const SENTENCES = [
  { id: "s1", hanzi: "雖然今天下雨，但是我還是要去學校。", pinyin: "Suī rán jīn tiān xià yǔ dàn shì wǒ hái shì yào qù xué xiào.", en: "Although it's raining today, I still have to go to school." },
  { id: "s2", hanzi: "我從早上八點忙到晚上七點，真的很累。", pinyin: "Wǒ cóng zǎo shàng bā diǎn máng dào wǎn shàng qī diǎn zhēn de hěn lèi.", en: "I've been busy from 8am to 7pm, I'm really tired." },
  { id: "s3", hanzi: "因為明天有考試，所以我今天晚上要在家準備。", pinyin: "Yīn wèi míng tiān yǒu kǎo shì suǒ yǐ wǒ jīn tiān wǎn shàng yào zài jiā zhǔn bèi.", en: "Because there's an exam tomorrow, I need to prepare at home tonight." },
  { id: "s4", hanzi: "你可以告訴我怎麼去火車站嗎？", pinyin: "Nǐ kě yǐ gàosu wǒ zěn me qù huǒ chē zhàn ma?", en: "Could you tell me how to get to the train station?" },
  { id: "s5", hanzi: "我覺得這個電影非常有意思，你要不要一起去看？", pinyin: "Wǒ jué de zhè gè diàn yǐng fēi cháng yǒu yì sī nǐ yào bù yào yī qǐ qù kàn?", en: "I think this movie is very interesting, do you want to go watch it together?" },
  { id: "s6", hanzi: "他已經學習漢語三年了，現在說得很好。", pinyin: "Tā yǐ jīng xué xí hàn yǔ sān nián le xiàn zài shuō de hěn hǎo.", en: "He has studied Chinese for three years, now he speaks it well." },
  { id: "s7", hanzi: "我想買一件衣服，但是這裡的東西都太貴了。", pinyin: "Wǒ xiǎng mǎi yī jiàn yī fú dàn shì zhè lǐ de dōngxi dōu tài guì le.", en: "I want to buy a piece of clothing, but everything here is too expensive." },
  { id: "s8", hanzi: "醫生說我需要多休息，不要每天工作到很晚。", pinyin: "Yī shēng shuō wǒ xū yào duō xiūxi bù yào měi tiān gōng zuò dào hěn wǎn.", en: "The doctor said I need to rest more, and not work late every day." },
  { id: "s9", hanzi: "明天天氣應該很好，我們一起去跑步吧。", pinyin: "Míng tiān tiān qì yīng gāi hěn hǎo wǒ men yī qǐ qù pǎo bù ba.", en: "Tomorrow's weather should be good, let's go running together." },
  { id: "s10", hanzi: "我的手機壞了，所以我今天沒辦法給你打電話。", pinyin: "Wǒ de shǒu jī huài le suǒ yǐ wǒ jīn tiān méi bàn fǎ gěi nǐ dǎ diàn huà.", en: "My phone is broken, so I couldn't call you today." },
  { id: "s11", hanzi: "我們從臺北坐火車到臺中，大概要兩個小時。", pinyin: "Wǒ men cóng tái běi zuò huǒ chē dào tái zhōng dà gài yào liǎng gè xiǎo shí.", en: "We're taking the train from Taipei to Taichung, it takes about two hours." },
  { id: "s12", hanzi: "她一邊唱歌一邊跳舞，大家都很高興。", pinyin: "Tā yī biān chàng gē yī biān tiào wǔ dà jiā dōu hěn gāo xīng.", en: "She sang while dancing, and everyone was happy." },
  { id: "s13", hanzi: "雖然這家餐廳的東西不便宜，但是很好吃，所以還是有很多人來。", pinyin: "Suī rán zhè jiā cān tīng de dōngxi bù biàn yí dàn shì hěn hǎo chī suǒ yǐ hái shì yǒu hěn duō rén lái.", en: "Although this restaurant's food isn't cheap, it's delicious, so a lot of people still come." },
  { id: "s14", hanzi: "你覺得學中文難不難？我覺得說話比寫字容易一點兒。", pinyin: "Nǐ jué de xué zhōng wén nán bù nán wǒ jué de shuō huà bǐ xiě zì róng yì yìdiǎnr.", en: "Do you think learning Chinese is hard? I think speaking is a little easier than writing." },
  { id: "s15", hanzi: "明天是我妹妹的生日，我們要一起去買蛋糕，然後去她家。", pinyin: "Míng tiān shì wǒ mèimei de shēng rì wǒ men yào yī qǐ qù mǎi dàn gāo rán hòu qù tā jiā.", en: "Tomorrow is my younger sister's birthday, we're going to buy a cake together, then go to her house." },
  { id: "s16", hanzi: "我在這家公司工作了兩年，同事對我都很好。", pinyin: "Wǒ zài zhè jiā gōng sī gōng zuò le liǎng nián tóng shì duì wǒ dōu hěn hǎo.", en: "I've worked at this company for two years, my colleagues are all good to me." },
  { id: "s17", hanzi: "現在是下午三點，我們還有兩個小時可以準備考試。", pinyin: "Xiàn zài shì xià wǔ sān diǎn wǒ men hái yǒu liǎng gè xiǎo shí kě yǐ zhǔn bèi kǎo shì.", en: "It's 3pm now, we still have two hours to prepare for the exam." },
  { id: "s18", hanzi: "他昨天生病了，所以今天沒有來上班。", pinyin: "Tā zuó tiān shēng bìng le suǒ yǐ jīn tiān méi yǒu lái shàng bān.", en: "He got sick yesterday, so he didn't come to work today." },
  { id: "s19", hanzi: "我覺得這個問題不太容易回答，你可以再說一次嗎？", pinyin: "Wǒ jué de zhè gè wèn tí bù tài róng yì huí dá nǐ kě yǐ zài shuō yī cì ma?", en: "I think this question isn't very easy to answer, could you say it again?" },
  { id: "s20", hanzi: "我們家附近有一個很大的公園，我常常去那裡運動。", pinyin: "Wǒ men jiā fù jìn yǒu yī gè hěn dà de gōng yuán wǒ cháng cháng qù nà lǐ yùn dòng.", en: "There's a big park near our house, I often go there to exercise." },
  { id: "s21", hanzi: "如果你有時間，可以來我家玩，我媽媽會做很多好吃的菜。", pinyin: "Rú guǒ nǐ yǒu shí jiān kě yǐ lái wǒ jiā wán wǒ māma huì zuò hěn duō hǎo chī de cài.", en: "If you have time, you can come play at my house, my mom will make a lot of delicious food." },
  { id: "s22", hanzi: "這件事情雖然很難，但是我相信你可以做得到。", pinyin: "Zhè jiàn shìqing suī rán hěn nán dàn shì wǒ xiāng xìn nǐ kě yǐ zuò de dào.", en: "Although this matter is difficult, I believe you can do it." },
  { id: "s23", hanzi: "我朋友說臺灣的水果又便宜又好吃，我很想去嚐嚐。", pinyin: "Wǒ péng yǒu shuō tái wān de shuǐ guǒ yòu biàn yí yòu hǎo chī wǒ hěn xiǎng qù cháng cháng.", en: "My friend says Taiwan's fruit is cheap and delicious, I really want to go try some." },
  { id: "s24", hanzi: "請問，從這裡到醫院怎麼走？大概要走多久？", pinyin: "Qǐng wèn cóng zhè lǐ dào yī yuàn zěn me zǒu dà gài yào zǒu duō jiǔ?", en: "Excuse me, how do I walk from here to the hospital? About how long does it take?" },
];
