// Starter content: HSK1–2 vocabulary and core grammar points.
// Traditional characters + Pinyin (tone marks) + English.
// Feel free to extend these arrays — the app reads them at load time.

const VOCAB = [
  { id: "v1", hanzi: "你", pinyin: "nǐ", en: "you", ex: { hanzi: "你好嗎？", pinyin: "Nǐ hǎo ma?", en: "How are you?" } },
  { id: "v2", hanzi: "我", pinyin: "wǒ", en: "I / me", ex: { hanzi: "我是學生。", pinyin: "Wǒ shì xuéshēng.", en: "I am a student." } },
  { id: "v3", hanzi: "他", pinyin: "tā", en: "he / him", ex: { hanzi: "他是我朋友。", pinyin: "Tā shì wǒ péngyǒu.", en: "He is my friend." } },
  { id: "v4", hanzi: "她", pinyin: "tā", en: "she / her", ex: { hanzi: "她是老師。", pinyin: "Tā shì lǎoshī.", en: "She is a teacher." } },
  { id: "v5", hanzi: "你好", pinyin: "nǐ hǎo", en: "hello", ex: { hanzi: "你好，很高興認識你。", pinyin: "Nǐ hǎo, hěn gāoxìng rènshi nǐ.", en: "Hello, nice to meet you." } },
  { id: "v6", hanzi: "謝謝", pinyin: "xièxie", en: "thank you", ex: { hanzi: "謝謝你的幫忙。", pinyin: "Xièxie nǐ de bāngmáng.", en: "Thanks for your help." } },
  { id: "v7", hanzi: "不客氣", pinyin: "bú kèqi", en: "you're welcome", ex: { hanzi: "不客氣，再見。", pinyin: "Bú kèqi, zàijiàn.", en: "You're welcome, goodbye." } },
  { id: "v8", hanzi: "對不起", pinyin: "duìbuqǐ", en: "sorry", ex: { hanzi: "對不起，我遲到了。", pinyin: "Duìbuqǐ, wǒ chídào le.", en: "Sorry, I'm late." } },
  { id: "v9", hanzi: "沒關係", pinyin: "méi guānxi", en: "it's okay / no problem", ex: { hanzi: "沒關係，不用擔心。", pinyin: "Méi guānxi, búyòng dānxīn.", en: "It's fine, don't worry." } },
  { id: "v10", hanzi: "再見", pinyin: "zàijiàn", en: "goodbye", ex: { hanzi: "明天見，再見！", pinyin: "Míngtiān jiàn, zàijiàn!", en: "See you tomorrow, bye!" } },
  { id: "v11", hanzi: "是", pinyin: "shì", en: "to be", ex: { hanzi: "這是我的書。", pinyin: "Zhè shì wǒ de shū.", en: "This is my book." } },
  { id: "v12", hanzi: "不", pinyin: "bù", en: "not / no", ex: { hanzi: "我不是老師。", pinyin: "Wǒ bú shì lǎoshī.", en: "I am not a teacher." } },
  { id: "v13", hanzi: "有", pinyin: "yǒu", en: "to have / there is", ex: { hanzi: "我有一隻貓。", pinyin: "Wǒ yǒu yì zhī māo.", en: "I have a cat." } },
  { id: "v14", hanzi: "沒有", pinyin: "méiyǒu", en: "to not have", ex: { hanzi: "我沒有錢。", pinyin: "Wǒ méiyǒu qián.", en: "I don't have money." } },
  { id: "v15", hanzi: "這", pinyin: "zhè", en: "this", ex: { hanzi: "這是誰的手機？", pinyin: "Zhè shì shéi de shǒujī?", en: "Whose phone is this?" } },
  { id: "v16", hanzi: "那", pinyin: "nà", en: "that", ex: { hanzi: "那是我的家。", pinyin: "Nà shì wǒ de jiā.", en: "That is my home." } },
  { id: "v17", hanzi: "誰", pinyin: "shéi", en: "who", ex: { hanzi: "他是誰？", pinyin: "Tā shì shéi?", en: "Who is he?" } },
  { id: "v18", hanzi: "什麼", pinyin: "shénme", en: "what", ex: { hanzi: "你叫什麼名字？", pinyin: "Nǐ jiào shénme míngzi?", en: "What is your name?" } },
  { id: "v19", hanzi: "哪裡", pinyin: "nǎlǐ", en: "where", ex: { hanzi: "你住在哪裡？", pinyin: "Nǐ zhù zài nǎlǐ?", en: "Where do you live?" } },
  { id: "v20", hanzi: "怎麼", pinyin: "zěnme", en: "how", ex: { hanzi: "這個字怎麼念？", pinyin: "Zhège zì zěnme niàn?", en: "How is this character pronounced?" } },
  { id: "v21", hanzi: "一", pinyin: "yī", en: "one", ex: { hanzi: "我有一個哥哥。", pinyin: "Wǒ yǒu yí ge gēge.", en: "I have one older brother." } },
  { id: "v22", hanzi: "二", pinyin: "èr", en: "two", ex: { hanzi: "現在兩點半。", pinyin: "Xiànzài liǎng diǎn bàn.", en: "It's 2:30 now." } },
  { id: "v23", hanzi: "三", pinyin: "sān", en: "three", ex: { hanzi: "他有三本書。", pinyin: "Tā yǒu sān běn shū.", en: "He has three books." } },
  { id: "v24", hanzi: "五", pinyin: "wǔ", en: "five", ex: { hanzi: "五點下班。", pinyin: "Wǔ diǎn xiàbān.", en: "Work ends at five." } },
  { id: "v25", hanzi: "十", pinyin: "shí", en: "ten", ex: { hanzi: "十分鐘後見。", pinyin: "Shí fēnzhōng hòu jiàn.", en: "See you in ten minutes." } },
  { id: "v26", hanzi: "今天", pinyin: "jīntiān", en: "today", ex: { hanzi: "今天天氣很好。", pinyin: "Jīntiān tiānqì hěn hǎo.", en: "The weather is nice today." } },
  { id: "v27", hanzi: "明天", pinyin: "míngtiān", en: "tomorrow", ex: { hanzi: "明天我要工作。", pinyin: "Míngtiān wǒ yào gōngzuò.", en: "I have to work tomorrow." } },
  { id: "v28", hanzi: "昨天", pinyin: "zuótiān", en: "yesterday", ex: { hanzi: "昨天我很忙。", pinyin: "Zuótiān wǒ hěn máng.", en: "I was busy yesterday." } },
  { id: "v29", hanzi: "現在", pinyin: "xiànzài", en: "now", ex: { hanzi: "你現在在哪裡？", pinyin: "Nǐ xiànzài zài nǎlǐ?", en: "Where are you now?" } },
  { id: "v30", hanzi: "點", pinyin: "diǎn", en: "o'clock", ex: { hanzi: "現在幾點？", pinyin: "Xiànzài jǐ diǎn?", en: "What time is it?" } },
  { id: "v31", hanzi: "爸爸", pinyin: "bàba", en: "dad", ex: { hanzi: "我爸爸是醫生。", pinyin: "Wǒ bàba shì yīshēng.", en: "My dad is a doctor." } },
  { id: "v32", hanzi: "媽媽", pinyin: "māma", en: "mom", ex: { hanzi: "媽媽在做飯。", pinyin: "Māma zài zuòfàn.", en: "Mom is cooking." } },
  { id: "v33", hanzi: "朋友", pinyin: "péngyǒu", en: "friend", ex: { hanzi: "他是我最好的朋友。", pinyin: "Tā shì wǒ zuì hǎo de péngyǒu.", en: "He's my best friend." } },
  { id: "v34", hanzi: "老師", pinyin: "lǎoshī", en: "teacher", ex: { hanzi: "老師，我有問題。", pinyin: "Lǎoshī, wǒ yǒu wèntí.", en: "Teacher, I have a question." } },
  { id: "v35", hanzi: "學生", pinyin: "xuéshēng", en: "student", ex: { hanzi: "她是大學學生。", pinyin: "Tā shì dàxué xuéshēng.", en: "She is a university student." } },
  { id: "v36", hanzi: "家", pinyin: "jiā", en: "home / family", ex: { hanzi: "我想回家。", pinyin: "Wǒ xiǎng huí jiā.", en: "I want to go home." } },
  { id: "v37", hanzi: "中國", pinyin: "Zhōngguó", en: "China", ex: { hanzi: "他來自中國。", pinyin: "Tā láizì Zhōngguó.", en: "He is from China." } },
  { id: "v38", hanzi: "台灣", pinyin: "Táiwān", en: "Taiwan", ex: { hanzi: "我在台灣學中文。", pinyin: "Wǒ zài Táiwān xué Zhōngwén.", en: "I'm learning Chinese in Taiwan." } },
  { id: "v39", hanzi: "學校", pinyin: "xuéxiào", en: "school", ex: { hanzi: "學校離這裡很近。", pinyin: "Xuéxiào lí zhèlǐ hěn jìn.", en: "The school is close to here." } },
  { id: "v40", hanzi: "醫院", pinyin: "yīyuàn", en: "hospital", ex: { hanzi: "醫院在銀行旁邊。", pinyin: "Yīyuàn zài yínháng pángbiān.", en: "The hospital is next to the bank." } },
  { id: "v41", hanzi: "吃", pinyin: "chī", en: "to eat", ex: { hanzi: "你吃早餐了嗎？", pinyin: "Nǐ chī zǎocān le ma?", en: "Have you eaten breakfast?" } },
  { id: "v42", hanzi: "喝", pinyin: "hē", en: "to drink", ex: { hanzi: "我想喝水。", pinyin: "Wǒ xiǎng hē shuǐ.", en: "I want to drink water." } },
  { id: "v43", hanzi: "水", pinyin: "shuǐ", en: "water", ex: { hanzi: "請給我一杯水。", pinyin: "Qǐng gěi wǒ yì bēi shuǐ.", en: "Please give me a glass of water." } },
  { id: "v44", hanzi: "茶", pinyin: "chá", en: "tea", ex: { hanzi: "台灣的茶很有名。", pinyin: "Táiwān de chá hěn yǒumíng.", en: "Taiwan's tea is famous." } },
  { id: "v45", hanzi: "咖啡", pinyin: "kāfēi", en: "coffee", ex: { hanzi: "我每天喝咖啡。", pinyin: "Wǒ měitiān hē kāfēi.", en: "I drink coffee every day." } },
  { id: "v46", hanzi: "蘋果", pinyin: "píngguǒ", en: "apple", ex: { hanzi: "這個蘋果很甜。", pinyin: "Zhège píngguǒ hěn tián.", en: "This apple is sweet." } },
  { id: "v47", hanzi: "去", pinyin: "qù", en: "to go", ex: { hanzi: "我要去學校。", pinyin: "Wǒ yào qù xuéxiào.", en: "I'm going to school." } },
  { id: "v48", hanzi: "來", pinyin: "lái", en: "to come", ex: { hanzi: "你可以來我家。", pinyin: "Nǐ kěyǐ lái wǒ jiā.", en: "You can come to my house." } },
  { id: "v49", hanzi: "看", pinyin: "kàn", en: "to see / watch / read", ex: { hanzi: "我喜歡看電影。", pinyin: "Wǒ xǐhuan kàn diànyǐng.", en: "I like watching movies." } },
  { id: "v50", hanzi: "聽", pinyin: "tīng", en: "to listen", ex: { hanzi: "我在聽音樂。", pinyin: "Wǒ zài tīng yīnyuè.", en: "I'm listening to music." } },
  { id: "v51", hanzi: "說", pinyin: "shuō", en: "to speak", ex: { hanzi: "他說中文說得很好。", pinyin: "Tā shuō Zhōngwén shuō de hěn hǎo.", en: "He speaks Chinese very well." } },
  { id: "v52", hanzi: "學習", pinyin: "xuéxí", en: "to study", ex: { hanzi: "我每天學習中文。", pinyin: "Wǒ měitiān xuéxí Zhōngwén.", en: "I study Chinese every day." } },
  { id: "v53", hanzi: "工作", pinyin: "gōngzuò", en: "work / job", ex: { hanzi: "他的工作很忙。", pinyin: "Tā de gōngzuò hěn máng.", en: "His job is very busy." } },
  { id: "v54", hanzi: "買", pinyin: "mǎi", en: "to buy", ex: { hanzi: "我想買一本書。", pinyin: "Wǒ xiǎng mǎi yì běn shū.", en: "I want to buy a book." } },
  { id: "v55", hanzi: "喜歡", pinyin: "xǐhuan", en: "to like", ex: { hanzi: "我喜歡喝茶。", pinyin: "Wǒ xǐhuan hē chá.", en: "I like drinking tea." } },
  { id: "v56", hanzi: "想", pinyin: "xiǎng", en: "to want / think", ex: { hanzi: "我想去台北。", pinyin: "Wǒ xiǎng qù Táiběi.", en: "I want to go to Taipei." } },
  { id: "v57", hanzi: "認識", pinyin: "rènshi", en: "to know (a person)", ex: { hanzi: "很高興認識你。", pinyin: "Hěn gāoxìng rènshi nǐ.", en: "Nice to meet you." } },
  { id: "v58", hanzi: "大", pinyin: "dà", en: "big", ex: { hanzi: "這間房子很大。", pinyin: "Zhè jiān fángzi hěn dà.", en: "This house is big." } },
  { id: "v59", hanzi: "小", pinyin: "xiǎo", en: "small", ex: { hanzi: "這隻貓很小。", pinyin: "Zhè zhī māo hěn xiǎo.", en: "This cat is small." } },
  { id: "v60", hanzi: "好", pinyin: "hǎo", en: "good", ex: { hanzi: "今天天氣很好。", pinyin: "Jīntiān tiānqì hěn hǎo.", en: "The weather is good today." } },
];

const GRAMMAR = [
  {
    id: "g1",
    title: "是 — identity sentences",
    explain: "Subject + 是 + Noun states what something is. Negate with 不是.",
    examples: [
      { hanzi: "我是學生。", pinyin: "Wǒ shì xuéshēng.", en: "I am a student." },
      { hanzi: "他不是老師。", pinyin: "Tā bú shì lǎoshī.", en: "He is not a teacher." },
    ],
  },
  {
    id: "g2",
    title: "的 — possession",
    explain: "Noun/pronoun + 的 + Noun shows possession, like 's in English.",
    examples: [
      { hanzi: "這是我的書。", pinyin: "Zhè shì wǒ de shū.", en: "This is my book." },
      { hanzi: "老師的手機在桌上。", pinyin: "Lǎoshī de shǒujī zài zhuō shàng.", en: "The teacher's phone is on the table." },
    ],
  },
  {
    id: "g3",
    title: "有 / 沒有 — existence & possession",
    explain: "有 means 'to have' or 'there is'. Negate with 沒有, not 不有.",
    examples: [
      { hanzi: "我有一隻貓。", pinyin: "Wǒ yǒu yì zhī māo.", en: "I have a cat." },
      { hanzi: "我沒有錢。", pinyin: "Wǒ méiyǒu qián.", en: "I don't have money." },
    ],
  },
  {
    id: "g4",
    title: "嗎 — yes/no questions",
    explain: "Add 嗎 to the end of a statement to turn it into a yes/no question.",
    examples: [
      { hanzi: "你是學生嗎？", pinyin: "Nǐ shì xuéshēng ma?", en: "Are you a student?" },
      { hanzi: "你喜歡喝茶嗎？", pinyin: "Nǐ xǐhuan hē chá ma?", en: "Do you like drinking tea?" },
    ],
  },
  {
    id: "g5",
    title: "Question words — 什麼 / 誰 / 哪裡 / 怎麼",
    explain: "Question words sit right where the answer would go — no word-order flip like in English.",
    examples: [
      { hanzi: "你叫什麼名字？", pinyin: "Nǐ jiào shénme míngzi?", en: "What is your name?" },
      { hanzi: "你住在哪裡？", pinyin: "Nǐ zhù zài nǎlǐ?", en: "Where do you live?" },
    ],
  },
  {
    id: "g6",
    title: "在 — location",
    explain: "在 + place marks where someone or something is, or where an action happens.",
    examples: [
      { hanzi: "我在家。", pinyin: "Wǒ zài jiā.", en: "I am at home." },
      { hanzi: "我在學校學中文。", pinyin: "Wǒ zài xuéxiào xué Zhōngwén.", en: "I study Chinese at school." },
    ],
  },
  {
    id: "g7",
    title: "了 — completed action",
    explain: "了 after a verb marks that the action happened or is finished.",
    examples: [
      { hanzi: "我吃了。", pinyin: "Wǒ chī le.", en: "I've eaten." },
      { hanzi: "他去了台北。", pinyin: "Tā qù le Táiběi.", en: "He went to Taipei." },
    ],
  },
  {
    id: "g8",
    title: "Time + Place + Verb order",
    explain: "Mandarin word order is Subject + Time + Place + Verb — the opposite tail-order from English.",
    examples: [
      { hanzi: "我今天在家看書。", pinyin: "Wǒ jīntiān zài jiā kàn shū.", en: "I'm reading at home today." },
    ],
  },
  {
    id: "g9",
    title: "想 / 要 — wanting to do something",
    explain: "想 (would like to) is softer than 要 (want to / will). Both go before a verb.",
    examples: [
      { hanzi: "我想去台灣。", pinyin: "Wǒ xiǎng qù Táiwān.", en: "I'd like to go to Taiwan." },
      { hanzi: "我要買一本書。", pinyin: "Wǒ yào mǎi yì běn shū.", en: "I want to buy a book." },
    ],
  },
  {
    id: "g10",
    title: "比 — comparisons",
    explain: "A + 比 + B + adjective means 'A is more [adjective] than B'.",
    examples: [
      { hanzi: "這個比那個大。", pinyin: "Zhège bǐ nàge dà.", en: "This one is bigger than that one." },
    ],
  },
  {
    id: "g11",
    title: "因為...所以... — because / so",
    explain: "因為 introduces the reason, 所以 introduces the result — often both appear in the same sentence.",
    examples: [
      { hanzi: "因為下雨，所以我在家。", pinyin: "Yīnwèi xiàyǔ, suǒyǐ wǒ zài jiā.", en: "Because it's raining, I'm staying home." },
    ],
  },
  {
    id: "g12",
    title: "可以 / 會 / 能 — three flavors of 'can'",
    explain: "可以 = allowed to; 會 = know how to (learned skill); 能 = physically/practically able to.",
    examples: [
      { hanzi: "你可以進來。", pinyin: "Nǐ kěyǐ jìnlái.", en: "You may come in." },
      { hanzi: "我會說中文。", pinyin: "Wǒ huì shuō Zhōngwén.", en: "I can speak Chinese." },
    ],
  },
];
